### ISSUE TITLE
[Bug]: CPU grows for steady state systems 

### ISSUE THREAD

**Issue by re250109** [vernemq/vernemq#2314] opened 2024-06-20 12:07 UTC
### Environment

- VerneMQ Version: 1.13.0
- OS: Ubuntu 20.04.6 LTS
- Erlang/OTP version (if building from source): 23.3.4
- Cluster size/standalone: ~ 12000 nodes 

### Current Behavior

When using vernemq at a high scale ( ~ 12000 connected clients) , we are seeing a steady CPU growth. 
![image](https://github.com/vernemq/vernemq/assets/137896134/a906026f-ffa4-4626-8902-9c0ea3ee14ca)
We tend to get a slow growth over a few days, and after it his a certain level we get  a sudden spike , after which vernemq stops responding.  Adding more CPU to the server does not seem to help at all - CPU use just grows to fill the room it has! 

We are seeing a steady stream of messages over the period of this growth, so I dont think it is down to an increasing load 
![counter queue_trend](https://github.com/vernemq/vernemq/assets/137896134/5f306dad-5b61-42a3-a5e0-9ba1df3e956b)

One worrying trend is the amount of system reductions and the words reclaimed - seems to be a huge number to me. And the reduction count seems to grow in ane exponential way, which might explain the CPU growth we see. 
![counter system_trend](https://github.com/vernemq/vernemq/assets/137896134/5b849471-cfb3-4b19-8875-a626d7c08342)

If i try to attach to the console and recon the process when it t has already seen a lot of CPU growth, I tend to see a lot of ets_select and gen_server

```
[{<0.9320.0>,3591317,
  [{current_function,{ets,select,1}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.9280.0>,3544871,
  [{current_function,{gen_server,loop,7}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.9289.0>,3543770,
  [{current_function,{ets,select,1}},
   {initial_call,{proc_lib,init_p,5}}]}]
```

```
[{<0.9190.0>,3737591,
  [{current_function,{ets,select,1}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.9328.0>,3656090,
  [{current_function,{ets,select,1}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.9311.0>,3653669,
  [{current_function,{ets,select,1}},
   {initial_call,{proc_lib,init_p,5}}]}]
```
There is a slight growth in ETS memory , but small compared to total memory volumes
![gauge vm_memory_trend](https://github.com/vernemq/vernemq/assets/137896134/9ee7cf4c-d116-4c1a-a572-14560b6039fb)

Sorry if this is not the right place for this

Help much appreciated 

### Expected behaviour

CPU trend stays level 

### Configuration, logs, error output, etc.

```markdown
# I have removed config points I believe could help identify the host 
allow_anonymous = off

allow_multiple_sessions = off
coordinate_registrations = on

max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000

listener.ssl.max_connections = 100
listener.tcp.max_connections = 1
listener.nr_of_acceptors = 10
listener.ssl.default = -
listener.ssl.cafile =  -
listener.ssl.certfile = -
listener.ssl.keyfile = -
listener.ssl.allowed_protocol_versions = 5
listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on
listener.ssl.depth = 2
listener.ssl.tls_version = tlsv1.2

systree_enabled = off
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000

plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = on
plugins.vmq_webhooks = off
plugins.vmq_bridge = off

metadata_plugin = vmq_plumtree
vmq_diversity.script_dir = /usr/share/vernemq/lua

log.console = both
log.console.level = info
log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = -
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by re250109** [comment] 2024-06-20 13:28
If helpful, this is the full metrics for the last data point on these graphs 
```
gauge.system_utilization_scheduler_55 = 0
gauge.system_utilization_scheduler_8 = 3
gauge.vm_memory_ets = 312356224
gauge.system_utilization_scheduler_43 = 0
gauge.system_utilization_scheduler_12 = 1
counter.mqtt_auth_received = 0
gauge.router_memory = 108287464
counter.queue_setup = 48099
gauge.system_utilization_scheduler_51 = 0
counter.mqtt_subscribe_auth_error = 0
counter.cluster_bytes_dropped = 0
counter.mqtt_auth_sent = 0
gauge.system_utilization_scheduler_40 = 0
gauge.system_utilization = 4
gauge.vm_memory_binary = 162095576
counter.system_runtime = 412401952
gauge.retain_messages = 113789
gauge.vm_memory_total = 1183654128
gauge.system_utilization_scheduler_28 = 0
counter.mqtt_pubrec_received = 0
gauge.system_utilization_scheduler_16 = 3
gauge.vm_memory_processes_used = 642684216
counter.mqtt_pubrec_sent = 0
counter.mqtt_publish_auth_error = 0
counter.socket_close = 50460
counter.mqtt_puback_received = 1322132
gauge.system_utilization_scheduler_6 = 10
gauge.system_utilization_scheduler_58 = 0
gauge.system_utilization_scheduler_31 = 0
gauge.system_utilization_scheduler_13 = 100
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_suback_sent = 131269
counter.mqtt_pubcomp_sent = 0
gauge.retain_memory = 71110960
counter.mqtt_publish_sent = 1323311
counter.socket_close_timeout = 45
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0
gauge.system_utilization_scheduler_18 = 1
counter.queue_message_out = 1323311
counter.mqtt_connack_unacceptable_protocol_sent = 0
gauge.router_subscriptions = 42311
gauge.system_utilization_scheduler_50 = 0
gauge.system_utilization_scheduler_37 = 0
counter.mqtt_puback_sent = 31725846
counter.system_gc_count = 236573278
counter.mqtt_connack_identifier_rejected_sent = 0
counter.client_keepalive_expired = 9665
counter.system_io_out = 25123438168
counter.mqtt_subscribe_received = 131269
gauge.system_utilization_scheduler_56 = 0
gauge.system_utilization_scheduler_41 = 0
gauge.system_utilization_scheduler_7 = 1
gauge.system_utilization_scheduler_62 = 0
counter.mqtt_connack_bad_credentials_sent = 0
counter.queue_message_drop = 20199
gauge.system_utilization_scheduler_34 = 0
gauge.system_utilization_scheduler_61 = 0
gauge.system_utilization_scheduler_32 = 0
gauge.system_utilization_scheduler_49 = 0
counter.mqtt_pubrel_received = 0
counter.mqtt_pubrel_sent = 0
gauge.vm_memory_system = 540845192
gauge.system_utilization_scheduler_10 = 23
gauge.system_utilization_scheduler_25 = 0
gauge.system_utilization_scheduler_46 = 0
counter.system_context_switches = 2199452299
counter.socket_open = 60853
gauge.system_utilization_scheduler_1 = 33
gauge.system_utilization_scheduler_24 = 0
gauge.system_utilization_scheduler_9 = 3
counter.queue_message_in = 1343641
counter.queue_message_expired = 136
counter.system_words_reclaimed_by_gc = 2914184204616
gauge.system_utilization_scheduler_36 = 0
gauge.system_utilization_scheduler_47 = 0
counter.mqtt_disconnect_sent = 13087
gauge.system_utilization_scheduler_21 = 0
counter.queue_message_unhandled = 0
gauge.system_utilization_scheduler_39 = 0
counter.mqtt_publish_error = 0
gauge.system_utilization_scheduler_53 = 0
counter.netsplit_resolved = 0
gauge.system_utilization_scheduler_22 = 0
counter.socket_error = 0
gauge.system_utilization_scheduler_26 = 0
gauge.system_process_count = 42101
counter.bytes_received = 3353406208
counter.bytes_sent = 868165360
counter.mqtt_unsuback_sent = 518
gauge.system_utilization_scheduler_57 = 0
gauge.system_utilization_scheduler_11 = 3
gauge.queue_processes = 10562
gauge.system_utilization_scheduler_42 = 0
counter.mqtt_connack_sent = 60807
gauge.system_utilization_scheduler_15 = 2
gauge.system_utilization_scheduler_20 = 0
gauge.vm_memory_code = 15173961
gauge.system_utilization_scheduler_19 = 2
counter.system_reductions = 2664876654048
counter.cluster_bytes_sent = 0
gauge.system_utilization_scheduler_17 = 7
counter.mqtt_pingresp_sent = 87855764
counter.queue_initialized_from_storage = 10456
gauge.system_utilization_scheduler_64 = 0
gauge.vm_memory_atom_used = 920442
counter.mqtt_disconnect_received = 33290
gauge.system_run_queue = 1
gauge.system_utilization_scheduler_48 = 0
gauge.system_utilization_scheduler_3 = 3
counter.mqtt_connack_accepted_sent = 0
gauge.system_utilization_scheduler_52 = 0
gauge.system_utilization_scheduler_30 = 0
counter.router_matches_remote = 0
gauge.system_utilization_scheduler_4 = 9
counter.mqtt_connect_received = 60807
counter.mqtt_unsubscribe_received = 518
gauge.system_utilization_scheduler_44 = 0
gauge.system_utilization_scheduler_14 = 28
counter.system_io_in = 7370422166
gauge.system_utilization_scheduler_33 = 0
gauge.system_utilization_scheduler_63 = 0
gauge.system_utilization_scheduler_45 = 0
gauge.active_mqttws_connections = 0
gauge.active_mqtt_connections = 10394
counter.mqtt_publish_received = 31725847
gauge.system_utilization_scheduler_38 = 0
counter.mqtt_pubrec_invalid_error = 0
gauge.system_utilization_scheduler_59 = 0
gauge.system_utilization_scheduler_54 = 0
counter.client_expired = 0
gauge.system_utilization_scheduler_5 = 10
counter.cluster_bytes_received = 0
gauge.system_utilization_scheduler_35 = 0
gauge.vm_memory_atom = 942329
counter.netsplit_detected = 0
counter.router_matches_local = 1311020
counter.system_wallclock = 171608901
gauge.system_utilization_scheduler_29 = 0
counter.system_exact_reductions = 2633256622140
counter.queue_teardown = 37537
gauge.system_utilization_scheduler_2 = 10
counter.mqtt_pubcomp_received = 0
gauge.system_utilization_scheduler_23 = 0
gauge.vm_memory_processes = 642808936
counter.mqtt_puback_invalid_error = 0
counter.mqtt_invalid_msg_size_error = 0
gauge.system_utilization_scheduler_27 = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_connack_not_authorized_sent = 0
gauge.system_utilization_scheduler_60 = 0
gauge.total_active_connections = 10394
counter.mqtt_pingreq_received = 87855764
```

**Comment by ioolkos** [comment] 2024-06-20 13:57
12k connections should be a breeze for a VerneMQ server. I don't immediately see an issue with your metrics.

As you only allow MQTT v5: can you set an upper limit for the inflight window:

```
receive_max_client = 20000
receive_max_broker = 20000
```
Also check for any OS contention (file descriptors, connections in CLOSE_WAIT?). I assume you're checking the logs as well.

Usually, I recommend `vmq_swc` over `vmq_plumtree` but that's just a side note, and not that important for a single node.

I'm a bit limited in time and options to be of concrete help, other than that. Good to see you found `recon`... ;)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment] 2024-06-23 14:29
`max_inflight_messages` only applies to MQTT 3.1.1 sessions. For MQTT 5 sessions, you have to use `receive_max_client`. The reason to set this is to have an upper limit... I have seen client sessions with QoS>0 getting stuck somehow with maximum settings (which is the default). I can't remember the MQTT client lib.

If you see huge "batches" of clients running into the keepalive timeout, your system clock might experience time jumps (or corrections)... is it a VM? This is an issue fixed in release `2.0.1`. Of course, this can also be caused by clients sending no ping requests.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment] 2024-06-24 12:48
@re250109 any update so far?
Btw do you have anything special in your setup (plugins? calls over HTTP api or anything like that?)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by re250109** [comment] 2024-06-24 14:09
Thanks for the above replies 
I have set the config points you suggested 
```
receive_max_client = 20000
receive_max_broker = 20000
```
And left it for a few days, but unfortunately no change 

If I look a bit closer I don't think we are seeing batches of the keep-alive error - it's a steady stream, and I think this is largely expected, some clients will exist in some pretty poor networks and disconnect now and then. (also we are aware of some issues with our client code that cause disconnects) . It is running in a VM, although AFAIK we are not having any clock jumps 

In terms of special stuff in the setup - the only thing I can think is that we are using custom ACL plugins in vmq-diversity. We largely do this so we can log all success/fail connection attempts and all publish failures , although there is some extra security we want to check on client register.  We have a 
specific hook for checking auth on publish:
```
function auth_on_publish(reg)
    if auth_cache.match_publish(reg.mountpoint .. "X", reg.client_id, reg.topic, reg.qos, reg.payload, reg.retain) == true then
        return true
    ...
```
We did look at your default [redis plugin](https://github.com/vernemq/vernemq/blob/main/apps/vmq_diversity/priv/auth/redis.lua) recently and noted that you have not specifically defined an on publish or subscribe check here , and in testing it seems like we didnt actually need to either.I dont really understand the mechanism but messages seem to have proper ACL run anyway . I know in earlier testing we did notice that adding our own custom ACL seemed to slow things down massively, so right now we are playing with removing the publish acl hook to see if this causes any improvement . 

We will also try a test run with vmq upgraded to 2.x to see if this impoves anything 👍

**Comment by ioolkos** [comment] 2024-06-24 14:26
This is probably not obvious, but you don't need to add Lua-based `auth_on_publish/auth_on_subscribe`.

`auth_on_register` will add the ACLs to the cache during register. Auth_on_publish then uses the cache (Erlang based), that's why you've seen them applied & working. Same for the subscribes.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by re250109** [comment] 2024-06-24 14:59
Yep , makes sense thank you 

We will do a proper test run tomorrow and see the comparative performance 👍 will let you know what we find 
I guess if we do find the issue is there , it is interesting that there seems to be some sort of CPU "leak" in the lua integration. I guess if we want to implement our own custom ACL on publish that logs when the publish check fails (as it does now), we would need to brave our own erlang plugin 

But thats getting ahead of ourselves... will let you know how we get on. (with that test, and also just trying a 2.x vernemq )

**Comment by re250109** [comment] 2024-07-03 10:08
Sorry for the slow reply here
Happy to say that removing our lua on message auth did fix the cpu "leak" 

![image](https://github.com/vernemq/vernemq/assets/137896134/329b22c5-cf60-4c18-844d-8c1d47f719a2)

Would you like me to leave this issue open? it seems that there is likely some bug here in the Lua code that causes this. I know having an unnecessary check on message would cause higher CPU, but i would expect this to be flat.  

But on the other hand, we only could create this when we ramped up the load a lot - not sure how easy it would be to recreate, and perhaps it is just not recommended to have any auth running on every message?  

Thanks for your help 🙏

**Comment by ioolkos** [comment] 2024-07-03 10:56
@re250109 Thanks for your feedback!

Might be a bug in the Lua layer, or just overload of the Lua layer (that's why I mentioned the `num_states` variable).
Since I don't have the (full) picture of the changes done and the load on the system, I think I'll close the issue for now.

But happy to re-open and look into it, if we can ever pinpoint this to a concrete code location.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Closed by ioolkos** 2024-07-03 10:56 UTC
Labels: bug
