### ISSUE TITLE
Beam.smp using 100% CPU

### ISSUE THREAD

**Issue by manish17mittal** [vernemq/vernemq#1284] opened 2019-08-07 15:53 UTC
Issue-
We are trying to create an instant chat application with the machine specified as below. When verneMQ is run, initially the messages are transferring successfully between users. But within a small amount of time, the CPU spikes to 100%, and thereafter no further messages could be sent through the server. All the 3 machines of our cluster reach 100% CPU usage and our application stops working.

Environment-
- VerneMQ Version: 3.2.2
- OS: Ubuntu 18.04, 16 cores, 64 GB RAM
- Erlang/OTP version (if building from source): -
- VerneMQ configuration (vernemq.conf) or the changes from the default: only defined the IP address for the machine. No other change.
- Cluster size/standalone: Using cluster of 3 nodes
- Load balancer is used

ERROR LOGS================================================
1. HTOP-

PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command                                                  13118 vernemq    20   0 16.3G 5239M  130M S 1600  8.3 31h01:04 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413509 vernemq    20   0 16.3G 5239M  130M R 100.  8.3 55:07.46 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413506 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  1h25:01 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413508 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  1h06:38 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413504 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  1h38:14 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413498 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  2h24:16 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413494 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  2h45:47 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413502 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  1h50:21 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413499 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  2h16:54 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413496 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  2h35:03 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413501 vernemq    20   0 16.3G 5239M  130M R 100.  8.3  1h58:35 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413495 vernemq    20   0 16.3G 5239M  130M R 99.7  8.3  2h38:57 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413507 vernemq    20   0 16.3G 5239M  130M R 99.7  8.3  1h16:36 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413500 vernemq    20   0 16.3G 5239M  130M R 99.7  8.3  2h07:22 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413503 vernemq    20   0 16.3G 5239M  130M R 99.7  8.3  1h43:51 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413505 vernemq    20   0 16.3G 5239M  130M R 99.3  8.3  1h32:01 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413497 vernemq    20   0 16.3G 5239M  130M R 98.6  8.3  2h31:57 
/usr/lib/vernemq/erts-10.2.3/bin/beam.smp -P 256000 -A 6413525 vernemq    20   0 16.3G 5239M  130M S  0.7  8.3  0:15.99

2. Crash.log-

 2019-08-07 11:03:52 =CRASH REPORT====
  crasher:
    initial call: plumtree_metadata_hashtree:init/1
    pid: <0.3567.0>
    registered_name: []
    exception error: {{badmatch,{error,{error_db_destroy,"IO error: lock /var/lib/vernemq/meta/trees/LOCK: already held by process"}}},[{hashtree,destroy,1,[{file,"/opt/vernemq/_build/default/lib/plumtree/src/hashtree.erl"},{line,262}]},{hashtree_tree,create_node,2,[{file,"/opt/vernemq/_build/default/lib/plumtree/src/hashtree_tree.erl"},{line,457}]},{hashtree_tree,new,2,[{file,"/opt/vernemq/_build/default/lib/plumtree/src/hashtree_tree.erl"},{line,187}]},{plumtree_metadata_hashtree,init,1,[{file,"/opt/vernemq/_build/default/lib/plumtree/src/plumtree_metadata_hashtree.erl"},{line,172}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [plumtree_sup,<0.201.0>]
    message_queue_len: 0
    messages: []
    links: [<0.203.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 329
  neighbours:
2019-08-07 11:03:52 =SUPERVISOR REPORT====
     Supervisor: {local,plumtree_sup}
     Context:    start_error
     Reason:     {{badmatch,{error,{error_db_destroy,"IO error: lock /var/lib/vernemq/meta/trees/LOCK: already held by process"}}},[{hashtree,destroy,1,[{file,"/opt/vernemq/_build/default/lib/plumtree/src/hashtree.erl"},{line,262}]},{hashtree_tree,create_node,2,[{file,"/opt/vernemq/_build/default/lib/plumtree/src/hashtree_tree.erl"},{line,457}]},{hashtree_tree,new,2,[{file,"/opt/vernemq/_build/default/lib/plumtree/src/hashtree_tree.erl"},{line,187}]},{plumtree_metadata_hashtree,init,1,[{file,"/opt/vernemq/_build/default/lib/plumtree/src/plumtree_metadata_hashtree.erl"},{line,172}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,{restarting,<0.228.0>}},{id,plumtree_metadata_hashtree},{mfargs,{plumtree_metadata_hashtree,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

3. Console.log-

2019-08-07 <IP_CLIENT_1> [warning] <0.14880.7>@vmq_mqtt_fsm:connected:431 client {[],<<"5053625:1565087737343">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_2> [warning] <0.16458.7>@vmq_mqtt_fsm:connected:431 client {[],<<"5022658:1565145472287">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_3> [warning] <0.20307.7>@vmq_mqtt_fsm:connected:431 client {[],<<"4015802:1561715560300">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_4> [warning] <0.20948.7>@vmq_mqtt_fsm:connected:431 client {[],<<"2729302:1565189319787">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_5> [warning] <0.21044.7>@vmq_mqtt_fsm:connected:431 client {[],<<"4503876:1563375292181">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_6> [warning] <0.19640.7>@vmq_mqtt_fsm:connected:431 client {[],<<"2754802:1564704109172">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_7> [warning] <0.20122.7>@vmq_mqtt_fsm:connected:431 client {[],<<"5035604:1565015794049">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_8> [warning] <0.21095.7>@vmq_mqtt_fsm:connected:431 client {[],<<"4883843:1564544155843">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_9> [warning] <0.8931.7>@vmq_mqtt_fsm:connected:431 client {[],<<"3337826:1558508855431">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_10> [warning] <0.20192.6>@vmq_mqtt_fsm:connected:431 client {[],<<"5085226:1565188479998">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_11> [warning] <0.20787.7>@vmq_mqtt_fsm:connected:431 client {[],<<"4791037:1564244064093">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_12> [warning] <0.19529.7>@vmq_mqtt_fsm:connected:431 client {[],<<"2801226:1554375099490">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_13> [warning] <0.14376.7>@vmq_mqtt_fsm:connected:431 client {[],<<"5046132:1565070656139">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_14> [warning] <0.15679.7>@vmq_mqtt_fsm:connected:431 client {[],<<"2082856:1565190580968">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_15> [warning] <0.20408.7>@vmq_mqtt_fsm:connected:431 client {[],<<"5067378:1565144270615">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_16> [warning] <0.22201.7>@vmq_ranch:teardown:143 session stopped abnormally due to 'badarg'
2019-08-07 <IP_CLIENT_17> [warning] <0.13717.7>@vmq_mqtt_fsm:connected:431 client {[],<<"5053189:1565086898912">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_18> [warning] <0.20475.7>@vmq_mqtt_fsm:connected:431 client {[],<<"4641894:1563772983273">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_19> [warning] <0.16681.7>@vmq_mqtt_fsm:connected:431 client {[],<<"3893811:1561191349641">>} with username <<"xyz">> stopped due to keepalive expired
2019-08-07 <IP_CLIENT_20> [warning] <0.22043.7>@vmq_mqtt_fsm:connected:431 client {[],<<"3654172:1564588990322">>} with username <<"xyz">> stopped due to keepalive expired

**Comment by larshesel** [comment] 2019-08-08 05:23
> VerneMQ Version: 3.2.2

The latest version is 1.9.0. Which version are you using?

> exception error: {{badmatch,{error,{error_db_destroy,"IO error: lock /var/lib/vernemq/meta/trees/LOCK: already held by process"}}}

This is strange and likely means you have two instances of VerneMQ running using the same message store.

> 2019-08-07 <IP_CLIENT_1> [warning] <0.14880.7>@vmq_mqtt_fsm:connected:431 client {[],<<"5053625:1565087737343">>} with username <<"xyz">> stopped due to keepalive expired

This means the client didn't send the PINGREQ (or VerneMQ didn't receive it) within the specified keepalive time in the CONNECT packet.

I'm afraid there isn't anything in the above which helps understanding the problem. If VerneMQ is using all the CPU then usually it is because it is being overloaded - but the issue doesn't say what you're doing how many messages per second, what the messaging patterns are, what the message sizes are etc.

I'll close this for now as there isn't any information here which indicates a bug in VerneMQ.

**Comment by manish17mittal** [comment] 2019-08-08 07:22
Sorry for the error, we are using VerneMQ version 1.8.0.

As for this error-
"exception error: {{badmatch,{error,{error_db_destroy,"IO error: lock /var/lib/vernemq/meta/trees/LOCK: already held by process"}}}"

we are running VerneMQ on a cluster of 3 nodes. Each node has a single VerneMQ process running. So, I don't understand two instances of VerneMQ using same message store because as far as I know VerneMQ uses in-memory LevelDB as it's message store.

As for this exception-
"2019-08-07 <IP_CLIENT_1> [warning] <0.14880.7>@vmq_mqtt_fsm:connected:431 client {[],<<"5053625:1565087737343">>} with username <<"xyz">> stopped due to keepalive expired"

ours is an instant messaging app. And the client starts the session with a certain keepalive timeout. The client can get disconnected from the broker before sending the PINGREQ packet due to several reasons (client closed the app/disconnected from internet, etc). In that case, the broker closes all the expired keepalive connections. Our concernis that the logs are filled up with these lines whenever we see CPU spike.

Attaching a screenshot of the vernemq status page that can give you the idea of the messages in and out rate. As our app is a regular chat application, message size totally depends upon what the user is sending. But it's usually between 80-120 bytes.

https://drive.google.com/file/d/1VP_49eJjn2iic0GegqZpAJr3KhwduDw8/view?usp=sharing

**Comment by larshesel** [comment] 2019-08-08 08:20
There must be some more going on - what is happening just before the cpu spikes? Were a node restarted? Do some of the metrics spike? 

Further, do you use random client-ids for the clients? The plumtree metadata backend doesn't garbage collect these and they stay around forever. Which means replicating these old client-ids can take a lot of cpu power. In such a case the swc metadata backend should be used. See https://vernemq.com/blog/2019/02/01/vernemq-next-level-replication.html for more information.

regarding:
> exception error: {{badmatch,{error,{error_db_destroy,"IO error: lock /var/lib/vernemq/meta/trees/LOCK: already held by process"}}}

Then there must also have happened something before this which leads to this error. I would observe and see if it happens again and note down what lead to it - that way it might be possible to form a hypothesis.

**Comment by larshesel** [comment] 2019-12-05 14:18
Hi @manish17mittal 

From another source we got some more info which led us to being able to reproduce the `exception error: {{badmatch,{error,{error_db_destroy,"IO error: lock /var/lib/vernemq/meta/trees/LOCK: already held by process"}}}` errors and subsequent node crash. I believe the fix for that should help you too - it's currently in review and can hopefully be merged soon for VerneMQ 1.10.1.

**Closed** 2019-12-06 08:39 UTC
