### ISSUE TITLE
Cannot trace anonymous users

### ISSUE THREAD

**Issue by SerialVelocity** [vernemq/vernemq#1673] opened 2020-11-12 17:33 UTC
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: 1.11.0
- OS: Kubernetes/Linux
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 2

### Expected behaviour

- Please describe the expected behaviour.
For the client ID to be correct when using an anonymous client ID. It looks like the last `=` is stripped.

This does seem to apply to other vmq-admin subcommands as well

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.
```
bash-4.4$ vmq-admin trace client 'client-id=anon-KGVkXp0VPF5jD9+1WIWPwwpzwWk='
2020-11-12T17:32:03Z No sessions found for client "anon-KGVkXp0VPF5jD9+1WIWPwwpzwWk"
```

**Comment by ioolkos** [comment] 2020-11-12 17:50
@SerialVelocity Thanks, yes, seems to be the case. The issue is in the clique command line parser, but I guess  we can prevent any `=` when generating the random client ID here: https://github.com/vernemq/vernemq/blob/7e8963fd645a22b4d2e0b8ffce94227ecb31ba21/apps/vmq_server/src/vmq_mqtt_fsm.erl#L1058

**Comment by ioolkos** [comment] 2020-11-26 17:15
@WojciechLuczkow jep, same thing. except it maybe means that the fix has to be in the parser, rather than generating the ClientID.

**Comment by WojciechLuczkow** [comment] 2020-11-27 14:10
I have raised issue in clique https://github.com/basho/clique/issues/91,
I also can prepare fix PR for that, which requires OTP 20.
VerneMq fork of clique uses OTP 18 - can it be upgraded?

**Comment by ioolkos** [comment] 2020-11-27 15:08
@WojciechLuczkow Verne fork is even with bash dev branch. Happy to accept your PR on Verne fork if there's no movement on upstream. This is unrelated to OTP 18 or 20, Verne has deprecated support for OTP 20 anyway.

**Comment by WojciechLuczkow** [comment] 2020-12-01 09:21
@ioolkos FYI I created PR for clique branch with fix, it is mentioned here,

**Comment by WojciechLuczkow** [comment] 2021-01-11 15:40
Hello,

Just reminding that MR for clique fork 
to start fixing this, and one more potential issue,
is ready.

**Comment by ioolkos** [comment] 2021-01-11 22:15
@WojciechLuczkow thanks for reminder, forgot about the PR, apologies. I'll look into it, this needs to work 100%, ie not break any other clique functionality.

**Comment by ioolkos** [comment] 2021-01-15 07:38
@WojciechLuczkow merged your clique PR (thanks!). What was the second downstream issue you wanted to fix?

**Comment by WojciechLuczkow** [comment] 2021-01-15 09:01
@ioolkos - I just noticed code will still behave wrongly if there is a value without key so fixed that in advance (with matching unit test). Now that clique branch is fixed I am starting PR to verne to fix this topic issue.

**Closed** 2024-03-04 21:51 UTC
Labels: enhancement, good first issue, fixes
