### ISSUE TITLE
Subscriber is online but not receiving messages

### ISSUE THREAD

**Issue by iotindustries** [vernemq/vernemq#1285] opened 2019-08-08 09:01 UTC
### Environment

- VerneMQ Version: 1.7.1
- OS: RHEL 7.6
- Erlang/OTP version (if building from source): n/a
- VerneMQ configuration - changes from the default: allow_anonymous = on, persistent_client_expiration = 1w, max_online_messages = 50000, listener.max_connections = 50000, listener.nr_of_acceptors = 1000, listener.tcp.default = <node_ip>:1883, listener.tcp.allowed_protocol_versions = 3,4,5,131, listener.vmq.clustering = <node_ip>:44053, listener.http.default = <node_ip>:8888, plugins.vmq_passwd = off, log.syslog = on, nodename = <node_name>, distributed_cookie = <text>, erlang.async.threads = 128, erlang.max_ports = 1000000, erlang.process_limit = 2000000

- Cluster size/standalone: 3 nodes

### Expected behavior
Subscriber is getting all messages within the subscribed topic while online.

### Actual behaviour
Subscriber stops receiving data within the subscribed topic while online.

### Details
Subscriber is correctly getting all messages within the subscribed topic. Suddenly he stops receiving all messages, but is still online. Other clients subscribed to same topic are receiving messages correctly. When the problematic client is restarted he immediately starts receiving messages.

Unfortunately, i did not find a way how to reproduce it. It just happens time-to-time without specific (known) reason. When it happened last time, the 'vmq-admin session show' was listing this client as online and subscribed to topic. The 'vmq-admin trace client' found session for this client and was logging the ping request/response events. So it all seems healthy, just nothing happens when message is published. If i trace another client subscribed to this topic, then i see the flow logged.

Level of logging is 'info' and there was nothing related to it. I want to change it to 'debug' for future occasion. 
Seems to me, i will need erlyberly to trace when it happens next time. Problem is it is a production system and erlyberly is not recommended to be used on production.

Any suggestions or ideas? Thank you very much.

**Comment by larshesel** [comment] 2019-08-08 09:43
You could use `recon` to trace (which we ship with vernemq). See http://ferd.github.io/recon/recon_trace.html.

You could also try to upgrade to 1.8.1 or 1.9.0 to see if it solves it. Without some kind of reproducing it I'm afraid there's little we can do to figure out what the issue is - so I'll close this for now, but feel free to reopen if more information becomes available.

**Closed by larshesel** 2019-08-08 09:43 UTC

**Comment by vikash1508** [comment] 2022-03-25 05:55
Did you find any solution to this problem?
This is happening to me as well, for 2 to 3 hours we are getting the subscribers are getting all the messages for the topic and after that, it is not receiving any messages for the topic but still, the publisher is publishing the messages.

**Comment by ioolkos** [comment] 2022-03-25 07:01
@vikash1508 
Is it possible to pack up the client side code into a script I could test? I need something reproducable to be able to help.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by vikash1508** [comment] 2022-03-25 11:41
Here is my code,
Language: Python3
Packages needed: paho-mqtt==1.6.1

For subscriber:
```

import paho.mqtt.client as mqtt_client
import time
import json
import threading
import logging, logging.handlers, atexit, sys

filename = 'LoadTest.csv'
logLevel = logging.INFO

formatter = logging.Formatter('%(asctime)s | %(levelname)s | %(message)s')
streamhandler = logging.StreamHandler(sys.stderr)
streamhandler.setLevel(logLevel)
streamhandler.setFormatter(formatter)
memoryhandler = logging.handlers.MemoryHandler(
    capacity=1024 * 100,
    flushLevel=logging.DEBUG,
    target=streamhandler
)

filehandler = logging.FileHandler(filename)
filehandler.setLevel(logLevel)
filehandler.setFormatter(formatter)

rotationHandler = logging.handlers.RotatingFileHandler(filename,
                                                       mode='a',
                                                       maxBytes=1024 *
1024 * 50,
                                                       backupCount=10,
                                                       delay=False)
rotationHandler.setLevel(logLevel)
rotationHandler.setFormatter(formatter)

logger = logging.getLogger()
logger.setLevel(logLevel)
logger.addHandler(memoryhandler)
logger.addHandler(filehandler)
logger.addHandler(rotationHandler)
def flush():
    memoryhandler.flush()
atexit.register(flush)
logging.debug("Logger has Initialized")

mqtt_url = "<LoadBalancerURL>"
mqtt_port = 1883

topics_for_test1 = "test/topic1"


def start(username, password, url, port, client_name):
    username = username
    password = password
    url = url
    port = port
    logging.critical("started connection")
    client = mqtt_client.Client(client_id=str(client_name))
    client.on_connect = on_connect
    client.on_message = on_messages
    client.on_publish = on_publish
    client.on_log = on_log
    client.on_disconnect = on_disconnect
    client.set_clean_session = True
    try:
        something = client.connect_async(host=url, port=port,
keepalive=60, bind_address='')
        logging.info("response from connection " + str(something))
    except Exception as err:
        logging.error("error = " + str(err))
        time.sleep(5)
        start(username, password, url, port)
    client.reconnect_delay_set(1, 5)
    client.loop_start()
    while True:
        time.sleep(60)
        try:
            if not client.is_connected():
                logging.error("MQTT is disconnected. retrying for
parking - " + str(client_name))
                client.reconnect()
                logging.error("MQTT is disconnected. retry success for
parking - " + str(client_name))
        except Exception as err:
            logging.error("MQTT re-connection failed for parking - " +
str(client_name) + ". error  -" + str(err))


def on_connect(client, userdata, flags, rc):
    logging.critical("connection success full")
    client.subscribe(topic=topics_for_test1, qos=2)


def on_messages(client, obj, msg):
    logging.info("Message received")


def on_log(client, obj, level, string):
    logging.debug("log - level - " + str(level) + " - message - " + str(string))


def on_publish(client, user_data, result):
    logging.info("message published")


def on_disconnect(client, userdata, rc):
    logging.critical("disconnected. rc - " + str(rc))


start("", "", mqtt_url, mqtt_port, "Subscriber-client-1")

```
For Publiser:
```

import paho.mqtt.client as mqtt_client
import time
import json
import threading
import logging, logging.handlers, atexit, sys

filename = 'LoadTest.csv'
logLevel = logging.INFO

formatter = logging.Formatter('%(asctime)s | %(levelname)s | %(message)s')
streamhandler = logging.StreamHandler(sys.stderr)
streamhandler.setLevel(logLevel)
streamhandler.setFormatter(formatter)
memoryhandler = logging.handlers.MemoryHandler(
    capacity=1024 * 100,
    flushLevel=logging.DEBUG,
    target=streamhandler
)

filehandler = logging.FileHandler(filename)
filehandler.setLevel(logLevel)
filehandler.setFormatter(formatter)

rotationHandler = logging.handlers.RotatingFileHandler(filename,
                                                       mode='a',
                                                       maxBytes=1024 *
1024 * 50,
                                                       backupCount=10,
                                                       delay=False)
rotationHandler.setLevel(logLevel)
rotationHandler.setFormatter(formatter)

logger = logging.getLogger()
logger.setLevel(logLevel)
logger.addHandler(memoryhandler)
logger.addHandler(filehandler)
logger.addHandler(rotationHandler)
def flush():
    memoryhandler.flush()
atexit.register(flush)
logging.debug("Logger has Initialized")

mqtt_url = "afeca372c6f4149c188e01b26b6fa2c0-1222942296.ap-south-1.elb.amazonaws.com"
mqtt_port = 1883
topics_for_test1 = "test/topic1"


def start(username, password, url, port, client_name):
    username = username
    password = password
    url = url
    port = port
    logging.critical("started connection")
    client = mqtt_client.Client(client_id=str(client_name))
    # client.username_pw_set(username, password=password)
    client.on_connect = on_connect
    client.on_message = on_messages
    client.on_publish = on_publish
    client.on_log = on_log
    client.on_disconnect = on_disconnect
    client.set_clean_session = True
    try:
        something = client.connect_async(host=url, port=port,
keepalive=60, bind_address='')
        logging.info("response from connection " + str(something))
    except Exception as err:
        logging.error("error = " + str(err))
        time.sleep(5)
        start(username, password, url, port)
    client.reconnect_delay_set(1, 5)
    client.loop_start()
    while True:
        time.sleep(5)
        try:
            if not client.is_connected():
                logging.error("MQTT is disconnected. retrying for
parking - " + str(client_name))
                client.reconnect()
                logging.error("MQTT is disconnected. retry success for
parking - " + str(client_name))
        except Exception as err:
            logging.error("MQTT re-connection failed for parking - " +
str(client_name) + ". error  -" + str(err))
        send(client, "test-message-1", topics_for_test1, client_name)


def on_connect(client, userdata, flags, rc):
    logging.critical("connection success full")
    client.subscribe(topic=topics_for_test1, qos=2)


def on_messages(client, obj, msg):
    logging.info("Message received")


def on_log(client, obj, level, string):
    logging.debug("log - level - " + str(level) + " - message - " + str(string))


def on_publish(client, user_data, result):
    logging.info("message published")


def on_disconnect(client, userdata, rc):
    logging.critical("disconnected. rc - " + str(rc))


def send(client, data, topic, user_name):
    logging.info("publishing data to topic")
    try:
        client.publish(topic, payload=json.dumps(data), qos=2)
    except Exception as err:
        logging.error("failed to publish message for user - " +
str(user_name) + ". error - " + str(err))


if __name__ == "__main__":
    thread = threading.Thread(target=start, args=("", "", mqtt_url,
mqtt_port, "Publisher-client-1"))
    thread.start()

```
For the Kubernetes cluster, I'm using AWS EKS and .yaml file for creating
the cluster is my question itself but passing here for reference:
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
name: vernemq
spec:
replicas: 1
selector:
matchLabels:
app: vernemq
serviceName: vernemq
template:
metadata:
labels:
app: vernemq
spec:
serviceAccountName: vernemq
terminationGracePeriodSeconds: 600
containers:
- name: vernemq
image: vernemq/vernemq:latest
# image: index.docker.io/chouhan/mqtt-docker:latest
# image: nmatsui/docker-vernemq:debug_insecure_kubernetes_restapi
imagePullPolicy: Always
lifecycle:
preStop:
exec:
command:
- /bin/bash
- -c
- /usr/sbin/vmq-admin cluster leave
node=VerneMQ@${MY_POD_NAME}.vernemq.${DOCKER_VERNEMQ_KUBERNETES_NAMESPACE}.svc.cluster.local
; sleep 60 ; /usr/sbin/vmq-admin cluster leave
node=VerneMQ@${MY_POD_NAME}.vernemq.${DOCKER_VERNEMQ_KUBERNETES_NAMESPACE}.svc.cluster.local
-k; sleep 60;
ports:
- containerPort: 1883
name: mqtt
hostPort: 1883
- containerPort: 8883
- containerPort: 4369
name: epmd
- containerPort: 44053
name: vmq
- containerPort: 8888
name: health
- containerPort: 9100
- containerPort: 9101
- containerPort: 9102
- containerPort: 9103
- containerPort: 9104
- containerPort: 9105
- containerPort: 9106
- containerPort: 9107
- containerPort: 9108
- containerPort: 9109
- containerPort: 8888
resources:
limits:
cpu: "1"
memory: 1Gi
requests:
cpu: "0.5"
memory: 0.5Gi
env:
- name: DOCKER_VERNEMQ_ACCEPT_EULA
value: "yes"
- name: MY_POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
value: "1"
- name: DOCKER_VERNEMQ_KUBERNETES_APP_LABEL
value: "vernemq"
- name: DOCKER_VERNEMQ_KUBERNETES_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
- name: DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MINIMUM
value: "9100"
- name: DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MAXIMUM
value: "9109"
- name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
value: "on"
- name: DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT
value: "0.0.0.0:1883"
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__POOL_timeout
value: "6000"
- name: DOCKER_VERNEMQ_LISTENER__HTTP__DEFAULT
value: "0.0.0.0:8888"
- name: DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS
value: "infinity"
- name: DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS
value: "10000"
- name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
value: "0"
- name: DOCKER_VERNEMQ_ALLOW_MULTIPLE_SESSIONS
value: "on"
- name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
value: "on"
- name: ALLOW_PUBLISH_DURING_NETSPLIT
value: "on"
- name: ALLOW_SUBSCRIBE_DURING_NETSPLIT
value: "on"
- name: ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
value: "on"
---
apiVersion: v1
kind: Service
metadata:
name: vernemq
labels:
app: vernemq
spec:
clusterIP: None
selector:
app: vernemq
ports:
- port: 4369
name: empd
- port: 44053
name: vmq
---
apiVersion: v1
kind: Service
metadata:
name: mqtt
labels:
app: mqtt
spec:
type: LoadBalancer
selector:
app: vernemq
ports:
- port: 1883
name: mqtt
targetPort: 1883
---
apiVersion: v1
kind: Service
metadata:
name: health
labels:
app: health
spec:
type: LoadBalancer
selector:
app: vernemq
ports:
- port: 8888
name: health
targetPort: 8888
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: vernemq
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: endpoint-reader
rules:
- apiGroups: ["", "extensions", "apps"]
resources: ["endpoints", "deployments", "replicasets", "pods"]
verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: endpoint-reader
subjects:
- kind: ServiceAccount
name: vernemq
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: endpoint-reader
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
name: vernemq
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: StatefulSet
name: vernemq
minReplicas: 1
maxReplicas: 4
targetCPUUtilizationPercentage: 80
```
