### ISSUE TITLE
cluster leave node and restart error

### ISSUE THREAD

**Issue by dcy** [vernemq/vernemq#194] opened 2016-09-01 07:57 UTC
Hi!
In one node of the cluster, I execute  ./bin/vmq-admin cluster leave node='VerneMQ@192.168.3.83'" and "./bin/vmq-admin cluster leave node='VerneMQ@192.168.3.83' -k", it works.

```
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster leave node='VerneMQ@192.168.3.83'
Done! Use -k to teardown and migrate existing sessions!
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster leave node='VerneMQ@192.168.3.83' -k
Done
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster status
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@192.168.3.82| true  |
+--------------------+-------+
```

But i start `VerneMQ@192.168.3.83`, The `VerneMQ@192.168.3.82` log shows:

```
2016-09-01 15:48:05.231 [info] <0.228.0>@vmq_cluster_mon:handle_info:126 Cluster Node 'VerneMQ@192.168.3.83' UP
2016-09-01 15:48:05.293 [info] <0.598.0>@plumtree_metadata_exchange_fsm:exchange:160 completed metadata exchange with 'VerneMQ@192.168.3.83'. repaired 0 missing local prefixes, 1 missing remote prefixes, and 0 keys
2016-09-01 15:48:15.905 [warning] <0.217.0>@vmq_reg_mgr:initiate_queue_migration:211 more than one remote nodes found for migrating queue[<0.390.0>] for subscriber {[],<<"18">>}, use 'VerneMQ@192.168.3.83'
2016-09-01 15:48:15.906 [info] <0.610.0>@plumtree_metadata_exchange_fsm:exchange:160 completed metadata exchange with 'VerneMQ@192.168.3.83'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 1 keys
2016-09-01 15:48:15.909 [error] <0.390.0>@vmq_queue:drain:299 can't drain queue '{[],<<"18">>}' for [<0.390.0>][<15891.237.0>] due to not_found
```

When i publish msg in `VerneMQ@192.168.3.82`, The log shows:

```
2016-09-01 15:52:09.879 [warning] <0.782.0>@vmq_reg:publish:305 can't publish to remote node 'VerneMQ@192.168.3.83' due to 'not_found'
```

When i publish msg in `VerneMQ@192.168.3.83`, The log also shows something about `VerneMQ@192.168.3.82`.
It seems the `VerneMQ@192.168.3.83` not leave the cluster completely.

**Comment by dergraf** [comment] 2016-09-02 08:02
@dcy after you did a cluster leave have you deleted the VerneMQ meta folder? If not the newly joined cluster gets into an undefined state, as the old node comes with old cluster-state information.

**Comment by dcy** [comment] 2016-09-03 09:22
@dergraf I did not delete anything.
It can reproduce. And after the leave node ```VerneMQ@192.168.3.83``` restart, The same client login ```VerneMQ@192.168.3.83``` will disconnect the same client in ```VerneMQ@192.168.3.82```.
It seems they are cluster still.
But the cluster status show they are not cluster.
```
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster status
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@192.168.3.83| true  |
+--------------------+-------+
```

**Comment by dergraf** [comment] 2016-09-03 09:44
If you want to rejoin you SHOULD delete the meta folder before rejoining.

**Comment by dcy** [comment] 2016-09-03 09:52
@dergraf I did not rejoin the left node. I only start the left node.

**Comment by dergraf** [comment] 2016-09-03 10:00
What was the status of the 192.168.3.83 node when you initiated the cluster leave? Online or offline?

**Comment by dcy** [comment] 2016-09-05 01:46
Online.
```
 ./bin/vmq-admin cluster leave node='VerneMQ@192.168.3.83'
 ./bin/vmq-admin cluster leave node='VerneMQ@192.168.3.83' -k
```

**Comment by dergraf** [comment] 2016-09-05 17:30
After the `cluster leave -k` did VerneMQ on 192.168.3.83 stop? If the cluster leave with an 'online' node succeeds the very last step would be to automatically stop VerneMQ.

**Comment by dcy** [comment] 2016-09-06 01:33
The VerneMQ on 192.168.3.83 stop. After 192.168.3.83 stop i start it, not join the node again.
Then the same client id login in 192.168.3.83 will disconnect it in 192.168.3.82.

**Comment by dergraf** [comment] 2016-09-06 21:09
I have an idea now what it could be. I try to reproduce it as soon as I can find time. Thank you for the issue report.

Remark (for futureme): 
Maybe leveldb hasn't been stopped correctly and updates haven't made it to disk.

**Comment by dergraf** [comment] 2016-10-26 19:37
Closed, due to inactivity

**Comment by dergraf** [comment] 2016-10-26 19:38
Has to be verified.

**Comment by qazwsx9006** [comment] 2018-03-09 06:17
I encounter the same problem too.

**Comment by dergraf** [comment] 2019-01-04 13:36
Closing this ancient issue. Please reopen and reverify with the latest VerneMQ version.

**Closed by dergraf** 2019-01-04 13:36 UTC
