### ISSUE TITLE
Moving containers around causes cluster to go down

### ISSUE THREAD

**Issue by Fossil01** [vernemq/vernemq#1824] opened 2021-06-16 09:10 UTC
I am running a stack of 3 VMQ container and 1 master container for container discovery purposes. Works fine.

I just set one Docker host to DRAIN and it moved some containers around, then the whole cluster stopped accepting connections and all my clients went down with it.

My guess is that (I did not see it) the master container was on the drained docker host and spun up on another host, and the already running VMQ containers could not find it anymore, essentially fucking up the cluster. They also complained that 3 cluster nodes were not reachable and the docs say that if a netsplit occurs (I don't know if 3-4 unreachable cluster nodes count as a netsplit) it stops accepting connections.

```
vernemq@9b128c6529b4:~$ vmq-admin cluster show
+---------------------+---------+
| Node                | Running |
+---------------------+---------+
| VerneMQ@10.0.11.230 | false   |
+---------------------+---------+
| VerneMQ@10.0.11.231 | true    |
+---------------------+---------+
| VerneMQ@10.0.11.232 | true    |
+---------------------+---------+
| VerneMQ@10.0.11.233 | true    |
+---------------------+---------+
| VerneMQ@10.0.11.234 | true    |
+---------------------+---------+
| VerneMQ@10.0.11.211 | false   |
+---------------------+---------+
| VerneMQ@10.0.11.222 | false   |
+---------------------+---------+
| VerneMQ@10.0.11.223 | false   |
+---------------------+---------+
| VerneMQ@10.0.11.229 | false   |
+---------------------+---------+
```

**Questions:**
1. Is it possible at all to move a running master container without consequences?
2. Why would 3-4 cluster members being down screw up the entire cluster?
3. Why are these cluster nodes not removed from the cluster automatically when the container exits?

In the end I fixed it by opening up a shell of one of the containers and manually removing the running=false nodes:
`vmq-admin cluster leave node="VerneMQ@10.0.11.229"`

Thanks!

**Comment by Fossil01** [comment] 2021-06-16 09:42
I have since learned about this PR https://github.com/vernemq/docker-vernemq/issues/191 which is merged and present in my container (running version 1.10.3).

The following code is present in `/usr/sbin/start_vernemq`

```bash
# SIGTERM-handler
sigterm_handler() {
    if [ $pid -ne 0 ]; then
        # this will stop the VerneMQ process, but first drain the node from all existing client sessions (-k)
        if [ -n "$VERNEMQ_KUBERNETES_HOSTNAME" ]; then
            terminating_node_name=VerneMQ@$VERNEMQ_KUBERNETES_HOSTNAME
        elif [ -n "$DOCKER_VERNEMQ_SWARM" ]; then
            terminating_node_name=VerneMQ@$(hostname -i)
        else
            terminating_node_name=VerneMQ@$IP_ADDRESS
        fi
        /vernemq/bin/vmq-admin cluster leave node=$terminating_node_name -k > /dev/null
        /vernemq/bin/vmq-admin node stop > /dev/null
        kill -s TERM ${pid}
        exit 0
    fi
}
```

Draining a docker node does not remove the containers I believe, it just stops them and spins up new ones on other nodes. Does this mean the SIGTERM handler is not called?

**Comment by ioolkos** [comment] 2021-06-16 09:46
@Fossil01 I do not know what DRAINing a Docker node is or implies. I'll have to read up on it.

**Comment by Fossil01** [comment] 2021-06-16 09:48
@ioolkos It just empties the host of all running containers and starts them on other hosts so you can do maintenance, reboot, troubleshoot etc.

**Comment by ioolkos** [comment] 2021-06-16 09:51
A netsplit situation occurs if any of the nodes is down. To be available in a netsplit you have to enable the `allow_register....etc` config values but I guess you have that. The issue is then likely related to the Docker draining.

**Comment by Fossil01** [comment] 2021-06-16 09:53
I have seen that and might change the config to allow subbing on netsplit etc. But I am more curious as of why my containers were not removed from the cluster prior to stopping the containers by Docker when I drained one host.

If it is removed from the cluster before going down then there should be no netsplit at all right? It should just continue running the cluster with one less member.

**Comment by Fossil01** [comment] 2021-10-12 10:49
Any info on my last post? :-)

**Comment by ioolkos** [comment] 2024-06-23 15:28
Closing due to no follow-ups on our part

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Closed by ioolkos** 2024-06-23 15:28 UTC
