### ISSUE TITLE
Postgres auth failing with some passwords

### ISSUE THREAD

**Issue by pramodhkp** [vernemq/vernemq#1202] opened 2019-05-29 13:42 UTC
### Environment

- VerneMQ Version: 1.8
- OS: Linux
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behavior

Should connect to postgres with the given username, host and password

### Actual behaviour

Does not connect to the postgres for some specific passwords with special chars in it. Throws out an error 
`13:41:32.509 [warning] Could not connect to postgresql due to invalid_password`

Example password: P1p0#7zpATJuFgyQdyP

**Comment by larshesel** [comment] 2019-05-31 06:25
Hi, can you show the sql statement you used to insert and hash the password?

**Comment by pramodhkp** [comment] 2019-05-31 07:07
I probably should have been more clear. This is not the ACL passwords I'm talking about. This is the `             DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD`. The user is created in a regular way with `CREATE USER` sql statement.

**Comment by larshesel** [comment] 2019-05-31 07:36
Aha, then I'd guess the problem is the `#` in the password which is written into the `vernemq.conf` file in which it is interpreted as a comment. I'm afraid there's nothing we can do about that without changing the configuration format which isn't currently planned.

**Comment by pramodhkp** [comment] 2019-05-31 07:43
Oh, that's bad. But isn't it like any other conf file? Does adding quotes around it help?

**Comment by dergraf** [comment] 2019-07-05 09:23
Closing the issue. Please reopen if the workaround doesn't work for you.

**Closed by dergraf** 2019-07-05 09:23 UTC

**Comment by sowjanya150** [comment] 2021-01-06 16:22
Hi,

I'm getting invalid_password error when i try to connect using **epgsqla:connect**  with correct password which does not contain special character. Is there anything else i need to check for this error? Please suggest.

Thank you!
