### ISSUE TITLE
Negative number value for offline clients

### ISSUE THREAD

**Issue by cmnstmntmn** [vernemq/vernemq#760] opened 2018-07-06 18:19 UTC
### Environment

- VerneMQ Version: vernemq_1.4.1-1
- OS: Debian stretch

### Expected behavior

not really sure

### Actual behaviour

in the status page, under the offline column i see a negative (-1 clients offline); 
does it make sense in a way?

![negative_offline_number](https://user-images.githubusercontent.com/2312755/42394253-295b4cb6-8162-11e8-9a71-55b3aca4edb5.jpg)

**Comment by ioolkos** [comment] 2018-07-09 09:03
@cmnstmntmn thanks, funny :)
- is it for WebSocket or TCP clients?
- is it a temporary effect?

it's possible that this is a transient effect in the counter math, for instance if a socket closes late.

**Comment by cmnstmntmn** [comment] 2018-07-09 09:41
@ioolkos tcp clients.

1. the value remain unchange during a page refresh;
2. i belive there there was a networking problem when i saw this, can't reproduce it anymore;

**Comment by dergraf** [comment] 2018-07-10 15:16
Closing for now.

**Comment by chamithchathuka** [comment] 2020-01-03 08:29
I am able to reproduce it. Checked no client is online shows offline clients in a negative numbers.

![Screenshot (35)](https://user-images.githubusercontent.com/17052727/71713765-1f340700-2e31-11ea-943c-824f8367abe2.png)

**Comment by vishnu-prasad-r** [comment] 2020-02-06 15:12
I am also experiencing the same problem.

![vernemq](https://user-images.githubusercontent.com/2042454/73950003-dece1a00-4903-11ea-82e8-ae130794249f.png)

**Comment by pijain** [comment] 2021-08-05 08:20
Did anyone found a solution or explanation to this behaviour, am facing this issue with VerneMQ 1.11 as well

**Comment by cmnstmntmn** [comment] 2021-08-10 14:13
@pijain can you inspect the network and look for the json edge data that is powering this page?
if those values are coming from there, then there is no problem with the javascript counter logic, otherwise
the counter is the problem.

**Comment by Tyraan** [comment] 2021-12-07 09:35
![image](https://user-images.githubusercontent.com/5787769/145004083-0530fac6-d6e5-4edd-8430-5bfd465d969b.png)

**Comment by Tyraan** [comment] 2021-12-07 09:35
same problem ,can someone tell me why ??

**Comment by ioolkos** [comment] 2021-12-07 13:26
@Tyraan 
It is a known issue and likely a bug in the `vmq_status_http` module, where a Verne nodes aggregates the node-local metrics with the cluster metrics (by doing RPC calls to the other nodes) to prepare data for the Status page.

This either happens in the aggregation, or because the TCP connection count is wrong to begin with. 
Does the "Client online" metric on the Status page seem to be correct?

To get realtime information on the active connections you can also attach** to a Verne node, and then get info on all Listeners with `ranch:info()` command: (check the `active_connections` part):
If `active_connections` are way off from what the Status page shows, we can conclude more.

**attach to Verne with: `sudo vernemq attach`
**detach with: `ctrl+g`, then at user switch type `q`

```sh
(VerneMQ@127.0.0.1)1> ranch:info().
[{{{0,0,0,0},44053},
  [{pid,<0.483.0>},
   {status,running},
   {ip,{0,0,0,0}},
   {port,44053},
   {max_connections,10000},
   {active_connections,0},
   {all_connections,0},
   {transport,ranch_tcp},
   {transport_options,#{max_connections => 10000,num_acceptors => 10,
                        socket_opts =>
                            [{ip,{0,0,0,0}},
                             {port,44053},
                             {nodelay,true},
                             {linger,{true,0}},
                             {send_timeout,30000},
                             {send_timeout_close,true}]}},
   {protocol,vmq_cluster_com},
   {protocol_options,[{max_connections,10000},
                      {nr_of_acceptors,10},
                      {mountpoint,[]},
                      {high_watermark,8192},
                      {low_watermark,4096},
                      {high_msgq_watermark,8192},
                      {low_msgq_watermark,4096}]}]},
 {{{127,0,0,1},1883},
  [{pid,<0.470.0>},
   {status,running},
   {ip,{127,0,0,1}},
   {port,1883},
   {max_connections,10000},
   {active_connections,0},
   {all_connections,0},
   {transport,ranch_tcp},
   {transport_options,#{max_connections => 10000,num_acceptors => 10,
                        socket_opts =>
                            [{ip,{127,0,0,1}},
                             {port,1883},
                             {nodelay,true},
                             {linger,{true,0}},
                             {send_timeout,30000},
                             {send_timeout_close,true}]}},
   {protocol,vmq_ranch},
   {protocol_options,[{mountpoint,[]},
                      {allowed_protocol_versions,[3,4,5]},
                      {buffer_sizes,undefined}]}]},
 {{{127,0,0,1},8888},
  [{pid,<0.496.0>},
   {status,running},
   {ip,{127,0,0,1}},
   {port,8888},
   {max_connections,10000},
   {active_connections,0},
   {all_connections,0},
   {transport,ranch_tcp},
   {transport_options,#{max_connections => 10000,num_acceptors => 10,
                        socket_opts =>
                            [{ip,{127,0,0,1}},
                             {port,8888},
                             {nodelay,true},
                             {linger,{true,0}},
                             {send_timeout,30000},
                             {send_timeout_close,true}]}},
   {protocol,cowboy_clear},
   {protocol_options,#{env =>
                           #{dispatch =>
                                 [{'_',[],
                                       [{[<<"metrics">>],[],vmq_metrics_http,[]},
                                        {[<<"api">>,<<...>>|...],[],vmq_http_mgmt_api,...},
                                        {[<<...>>],[],...},
                                        {[...],...},
                                        {...}|...]}]}}}]},
 {{{0,0,0,0,0,0,0,0},1882},
  [{pid,<0.457.0>},
   {status,running},
   {ip,{0,0,0,0,0,0,0,0}},
   {port,1882},
   {max_connections,10000},
   {active_connections,0},
   {all_connections,0},
   {transport,ranch_tcp},
   {transport_options,#{max_connections => 10000,num_acceptors => 10,
                        socket_opts =>
                            [{ip,{0,0,0,0,0,0,0,0}},
                             {port,1882},
                             {nodelay,true},
                             {linger,{true,0}},
                             {send_timeout,30000},
                             {send_timeout_close,true}]}},
   {protocol,vmq_ranch},
   {protocol_options,[{mountpoint,[]},
                      {allowed_protocol_versions,[3,4,131]},
                      {buffer_sizes,undefined}]}]}]
```
---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by hadrava** [comment] 2021-12-14 18:25
Same issue here, Running VerneMQ 1.11.0 on 12 independent instances (all of them have very similar setup).

In all cases, the total number of clients Online + Offline was equal to output of command `vmq-admin session show`. The offline client count was always negative. There seems to be a correlation between negative offline client count (or online client count, because the sum is correct) and active connections on WebSocket port (obtained using `ss -n 'sport = 1884' | wc -l` command (minus 1 for header)).

instance        |offline clients        |WebSocket connections
--|--|--
1       |-335   |253
2       |-645   |282
3       |-15    |26
4       |-97    |33
5       |-4     |11
6       |-79    |38
7       |-6     |7
8       |-2     |7
9       |-305   |114
10      |-72    |26
11      |-77    |27
12      |-47    |27

![vernemq](https://user-images.githubusercontent.com/9431955/142744190-83f0f38a-4f2b-48e4-aaeb-f39130019add.png)
That was measured few weeks ago, before we restarted everything.

Running the `ranch:info()` today on one particular instance (number 2):
 - status webpage: 58 online, -42 offline (total 16)
 - `vmq-admin session show`: total 16 clients, 10 of them should be TCP, 6 on WS
 - `ss -n 'sport = 1883'`: 10 TCP connections
 - `ss -n 'sport = 1884'`: 21 connections on WebSocket port
 - `ranch:info()`
 ```
(VerneMQ@10.11.2.100)1> ranch:info().
[{{{10,11,2,100},1883},
  [{pid,<0.369.0>},
   {status,running},
   {ip,{10,11,2,100}},
   {port,1883},
   {max_connections,10000},
   {active_connections,10},
   {all_connections,10},
   {transport,ranch_tcp},
   {transport_options,#{max_connections => 10000,num_acceptors => 10,
                        socket_opts =>
                            [{ip,{10,11,2,100}},
                             {port,1883},
                             {nodelay,true},
                             {linger,{true,0}},
                             {send_timeout,30000},
                             {send_timeout_close,true}]}},
   {protocol,vmq_ranch},
   {protocol_options,[{mountpoint,[]},
                      {allowed_protocol_versions,[3,4,131]},
                      {buffer_sizes,undefined}]}]},
 {{{10,11,2,100},1884},
  [{pid,<0.383.0>},
   {status,running},
   {ip,{10,11,2,100}},
   {port,1884},
   {max_connections,10000},
   {active_connections,0},
   {all_connections,21},
   {transport,ranch_tcp},
   {transport_options,#{max_connections => 10000,num_acceptors => 10,
                        socket_opts =>
                            [{ip,{10,11,2,100}},
                             {port,1884},
                             {nodelay,true},
                             {linger,{true,0}},
                             {send_timeout,30000},
                             {send_timeout_close,true}]}},
   {protocol,cowboy_clear},
   {protocol_options,#{env =>
                           #{dispatch =>
                                 [{'_',[],[{[<<"mqtt">>],[],vmq_websocket,[{...}|...]}]}]},
                       stream_handlers =>
                           [vmq_cowboy_websocket_h,cowboy_stream_h]}}]},
 {{{10,11,2,100},8888},
  [{pid,<0.409.0>},
   {status,running},
   {ip,{10,11,2,100}},
   {port,8888},
   {max_connections,10000},
   {active_connections,0},
   {all_connections,0},
   {transport,ranch_tcp},
   {transport_options,#{max_connections => 10000,num_acceptors => 10,
                        socket_opts =>
                            [{ip,{10,11,2,100}},
                             {port,8888},
                             {nodelay,true},
                             {linger,{true,0}},
                             {send_timeout,30000},
                             {send_timeout_close,true}]}},
   {protocol,cowboy_clear},
   {protocol_options,#{env =>
                           #{dispatch =>
                                 [{'_',[],
                                       [{[<<"metrics">>],[],vmq_metrics_http,[]},
                                        {[<<"api">>,<<...>>|...],[],vmq_http_mgmt_api,...},
                                        {[<<...>>],[],...},
                                        {[...],...},
                                        {...}|...]}]}}}]},
 {{{127,0,0,1},44053},
  [{pid,<0.396.0>},
   {status,running},
   {ip,{127,0,0,1}},
   {port,44053},
   {max_connections,10000},
   {active_connections,0},
   {all_connections,0},
   {transport,ranch_tcp},
   {transport_options,#{max_connections => 10000,num_acceptors => 10,
                        socket_opts =>
                            [{ip,{127,0,0,1}},
                             {port,44053},
                             {nodelay,true},
                             {linger,{true,0}},
                             {send_timeout,30000},
                             {send_timeout_close,true}]}},
   {protocol,vmq_cluster_com},
   {protocol_options,[{max_connections,10000},
                      {nr_of_acceptors,10},
                      {mountpoint,[]},
                      {high_watermark,8192},
                      {low_watermark,4096},
                      {high_msgq_watermark,8192},
                      {low_msgq_watermark,4096}]}]}]
```

All the 15 still opened ports on WebSocket which are not found in the `vmq-admin session show` are caused by just 4 computers on WiFi. I do not know much more about them.

**Comment by hadrava** [comment] 2021-12-17 19:08
I looked inside `vmq_status_http` code and compared it with other observations:
```
    % Total Connections
    SocketOpen = counter_val(?METRIC_SOCKET_OPEN),
    SocketClose = counter_val(?METRIC_SOCKET_CLOSE),
    TotalConnections = SocketOpen - SocketClose,
    % Total Online Queues
    TotalQueues = vmq_queue_sup_sup:nr_of_queues(),
    TotalOfflineQueues = TotalQueues - TotalConnections,
```
The `TotalConnections` seems to be wrong because of strange counts in metrics:
```
$ vmq-admin metrics show | grep socket
counter.socket_close = 107554
counter.socket_close_timeout = 0
counter.socket_open = 107620
counter.socket_error = 0
```
Difference is 66, which explains why the status page is currently showing 66 clients online. (And -45 offline, because there is 21 sessions/queues in total (`vmq-admin session show`))

I don't believe those `socket_close`/`socket_open` counters in metrics. Especially because `ss -n 'sport = 1883'` and `ss -n 'sport = 1884'` are reporting 12 and 20 opened connections (same as `ranch:info().`).

(Note, that real opened socket count would still lead to strange numbers (31 online and -10 offline), because 10 of the websocket connections are not containing any valid mqtt session and they are not associated with any queue.)

**Comment by ioolkos** [comment] 2021-12-17 20:07
@hadrava thanks for your investigation!

The idea with `TotalOfflineQueues = TotalQueues - TotalConnections` originally was this: Every online MQTT client has a queue, in any case. If we have 100 clients online, we have 100 queues. Let's say we have an additional 20 offline queues (for clients that requested persistent sessions but are currently offline). We'd then have a queue count of 120, and a connection count of 100, and therefore can conclude that currently we have 20 offline queues.

So to end up in the negative numbers, we either have a TotalConnection count that is too high at this point; or a TotalQueues count that is too low...


---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment] 2022-12-09 21:52
I currently see the same thing. We have negative number of offline clients. I attached to vernemq and checked the TotalQueues (vmq_queue_sup_sup:nr_of_queues()) which is correct (as I do have a very small test setup I can tell). My guess is as well, that not all closed sessions are catched by VerneMQ leading to wrong numbers.

**Comment by ioolkos** [comment] 2022-12-10 10:01
@mths1 yeah, that's what likely happens. We should implement an additional gauge `active_connections` (using `ranch:info`) for this kind of metrics.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment] 2023-01-21 18:41
I was able to reproduce our case. 

Most basic example:

Two Nodes 
- A 
- B
- One persistent subscriber

Steps:
- Create a persistent session (subscribe) on Node A (e.g. via CLI)
- Now we stop Node A (without leaving the cluster)
- Try to reconnect the persistent session to Node B (in real-world this would be our LB who redirects to B)
- The first attempt to connect fails
- The second attempt works

In the logs there is the following error:
2023-01-21 19:35:38.707 [error] <0.14466.0>@vmq_reg:-register_subscriber_/6-fun-0-:247 CRASH REPORT Process <0.14466.0> with 0 neighbours crashed with reason: no case clause matching {badrpc,nodedown} in vmq_reg:'-register_subscriber_/6-fun-0-'/2 line 247

- Restart Node A

Now you see offline clients -1, you can repeat the steps for -2,...

**Comment by ioolkos** [comment] 2023-01-22 11:16
@mths1 okay, thanks!

So we have at least 1 reproducible situation now. We probably want to catch that `badrpc`. 

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment] 2023-01-24 08:39
@mths1 quick question: the first re-connect always fails? also: how fast do you go through your  steps, for instance between creating the first persistent session and stopping node A?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment] 2023-01-24 10:20
In my lab setup I do all the steps manually, so there are a few seconds between each step. I just waited five minutes before reconnecting and it still fails. Currently, it seems as if all reconnects fail.

**Comment by ioolkos** [comment] 2023-01-24 11:00
@mths1 ok, thanks. You could also take note of the queue count, before, during and after node A restart. `vmq_queue_sup_sup:nr_of_queues().`

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pselvam-p44** [comment] 2023-05-04 02:51
> I am able to reproduce it. Checked no client is online shows offline clients in negative numbers.
> 
> ![Screenshot (35)](https://user-images.githubusercontent.com/17052727/71713765-1f340700-2e31-11ea-943c-824f8367abe2.png)

what is the solution for this ?

**Comment by mths1** [comment] 2023-05-04 08:02
@pselvam-p44 : The problem is fixed should not appear on "main" branch anymore.

**Closed** 2024-03-04 21:39 UTC
