### ISSUE TITLE
1.12.5 postgres diversity plugin crash

### ISSUE THREAD

**Issue by tobdub** [vernemq/vernemq#1967] opened 2022-03-23 16:24 UTC
### Environment

- VerneMQ Version: 1.12.5
- OS: Docker - Alpine 3.15
- Erlang/OTP version (if building from source): 23
- VerneMQ configuration (vernemq.conf) or the changes from the default: N/A
- Cluster size/standalone: 1 node

### Expected behaviour

postgres diversity auth should work.

### Actual behaviour

postgres diversity plugin crash:

```
17:34:01.068 [error] can't call function auth_on_register with args [{addr,<<"172.17.0.4">>},{port,47272},{mountpoint,<<>>},{client_id,<<"anon-Uk4+w1XsBbtHGGT3b6aIiAl/+vI=">>},{username,<<"testuser">>},{password,<<"testuser">>},{clean_session,true}] in "./share/lua/auth/postgres.lua" due to {error,function_clause}
17:34:01.069 [warning] can't authenticate client {[],<<"anon-Uk4+w1XsBbtHGGT3b6aIiAl/+vI=">>} from 172.17.0.4:47272 due to lua_script_error
```

Everything works fine in 1.12.4

**Comment by ioolkos** [comment] 2022-03-26 09:00
@tobdub thanks for reporting. Do you see the same error when compiling with an OTP 24 Erlang version?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tobdub** [comment] 2022-03-28 08:24
Yes, same result with OTP 24. Also, when compiling with OTP 23 there are some warnings about use of deprecated functions that will be removed in OTP 24.

**Comment by meteoiker** [comment] 2022-03-31 10:41
I only want to add this error also happens to me. Using OTP23 and OTP24 with ubuntu buster on docker. I have done more investigation and the problem only occurs when the query in db_library.execute() returns a result (either sever side crypt or client side bcrypt). If I use wrong credentials the result is simply a "Connection Refused: bad user name or password.", but using correct credentials a "Connection Refused: not authorised." error is thrown using mosquitto clients.

**Comment by ioolkos** [comment] 2022-03-31 14:08
Does the Postgres user, you've configured in the `vernemq.conf` file have access to the `vmq_auth_acl` table?

If yes, then it looks like the epgsql `4.6.0` version breaks things here.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment] 2022-03-31 15:24
Tested with a local setup and can reproduce it. 

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment] 2022-03-31 17:13
Could you help test whether my PR https://github.com/vernemq/vernemq/pull/1975 fixes this issue?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment] 2022-04-02 08:25
@tobdub @meteoiker I've merged the fix into the main branch. Could you help test the issue is fixed on your side?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tobdub** [comment] 2022-04-04 09:43
This solved the issue for me. Thanks!

**Comment by ioolkos** [comment] 2022-04-11 05:53
fixed by: https://github.com/vernemq/vernemq/pull/1975

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Closed by ioolkos** 2022-04-11 05:53 UTC
Labels: bug, vmq_diversity, 1.12.5
