### ISSUE TITLE
Client terminated with reason: no case clause matching #vmq_msg{}

### ISSUE THREAD

**Issue by boboxiaodd** [vernemq/vernemq#1045] opened 2019-01-22 03:56 UTC
### Environment

- VerneMQ Version: 1.6.2
- OS: centos7
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behavior
error logger:
```erlang
2019-01-21 20:09:00.013 [error] <0.29450.2>@vmq_mqtt_fsm:connected:334 Ranch listener {{0,0,0,0},9000} terminated with reason: no case clause matching {vmq_msg,<<55,217,248,92,235,34,154,74,102,128,125,245,72,149,69,45>>,[<<"u_70000026">>,<<"message">>],<<...>>,...} in vmq_mqtt_fsm:connected/2 line 334
```

i check source ：
```erlang
connected(#mqtt_pubcomp{message_id=MessageId}, State) ->
    #state{waiting_acks=WAcks} = State,
    %% qos2 flow
    _ = vmq_metrics:incr_mqtt_pubcomp_received(),
    case maps:get(MessageId, WAcks, not_found) of
        #mqtt_pubrel{} ->
            handle_waiting_msgs(State#state{
                                  waiting_acks=maps:remove(MessageId, WAcks)});
        not_found -> % error or wrong waiting_ack, definitely not well behaving client
            lager:debug("stopped connected session, due to qos2 pubrel missing ~p", [MessageId]),
            _ = vmq_metrics:incr_mqtt_error_invalid_pubcomp(),
            terminate(normal, State)
    end;
```

i don't konw why `WAcks` matched `#vmq_msg{}`

**Comment by dergraf** [comment] 2019-01-22 08:02
Can you reproduce this with this particular client id?

**Comment by boboxiaodd** [comment] 2019-01-22 08:13
maybe client send pubcomp delay ,and other msg come in ?

**Comment by boboxiaodd** [comment] 2019-01-23 04:41
```erlang
10:35:22.881 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {mqtt_pubrel,1}}

10:35:22.882 [info] prepare_frame:918 prepare_frame waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.883 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.884 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.885 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.886 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.887 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.888 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.889 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.890 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.890 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.891 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.892 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.893 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.894 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.895 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.896 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.897 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.898 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.898 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.899 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.900 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.901 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.902 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.903 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.904 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.905 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.905 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.906 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.907 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.908 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.909 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.910 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}
```


something change ..
```erlang
10:35:22.911 [info] handle_messages:873 deliver_pubrel waiting_acks:#{48 => {mqtt_pubrel,48},39 => {mqtt_pubrel,39},34 => {mqtt_pubrel,34},26 => {mqtt_pubrel,26},20 => {mqtt_pubrel,20},50 => {mqtt_pubrel,50},25 => {mqtt_pubrel,25},44 => {mqtt_pubrel,44},36 => {mqtt_pubrel,36},1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}


10:35:22.911 [info] handle_messages:873 deliver_pubrel waiting_acks:#{48 => {mqtt_pubrel,48},39 => {mqtt_pubrel,39},34 => {mqtt_pubrel,34},26 => {mqtt_pubrel,26},20 => {mqtt_pubrel,20},50 => {mqtt_pubrel,50},25 => {mqtt_pubrel,25},44 => {mqtt_pubrel,44},36 => {mqtt_pubrel,36},1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}


10:35:22.912 [info] handle_messages:873 deliver_pubrel waiting_acks:#{48 => {mqtt_pubrel,48},39 => {mqtt_pubrel,39},34 => {mqtt_pubrel,34},26 => {mqtt_pubrel,26},52 => {mqtt_pubrel,52},20 => {mqtt_pubrel,20},50 => {mqtt_pubrel,50},25 => {mqtt_pubrel,25},44 => {mqtt_pubrel,44},36 => {mqtt_pubrel,36},1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}


10:35:22.913 [info] handle_messages:873 deliver_pubrel waiting_acks:#{48 => {mqtt_pubrel,48},39 => {mqtt_pubrel,39},34 => {mqtt_pubrel,34},26 => {mqtt_pubrel,26},52 => {mqtt_pubrel,52},20 => {mqtt_pubrel,20},50 => {mqtt_pubrel,50},25 => {mqtt_pubrel,25},44 => {mqtt_pubrel,44},36 => {mqtt_pubrel,36},1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}


10:35:22.914 [info] handle_messages:873 deliver_pubrel waiting_acks:#{48 => {mqtt_pubrel,48},39 => {mqtt_pubrel,39},34 => {mqtt_pubrel,34},26 => {mqtt_pubrel,26},52 => {mqtt_pubrel,52},20 => {mqtt_pubrel,20},50 => {mqtt_pubrel,50},25 => {mqtt_pubrel,25},44 => {mqtt_pubrel,44},36 => {mqtt_pubrel,36},1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

10:35:22.915 [info] handle_messages:873 deliver_pubrel waiting_acks:#{48 => {mqtt_pubrel,48},39 => {mqtt_pubrel,39},34 => {mqtt_pubrel,34},26 => {mqtt_pubrel,26},52 => {mqtt_pubrel,52},20 => {mqtt_pubrel,20},50 => {mqtt_pubrel,50},25 => {mqtt_pubrel,25},44 => {mqtt_pubrel,44},36 => {mqtt_pubrel,36},1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}


10:35:23.707 [info] connected:336 connected mqtt_pubcomp WAcks: #{48 => {mqtt_pubrel,48},39 => {mqtt_pubrel,39},34 => {mqtt_pubrel,34},26 => {mqtt_pubrel,26},52 => {mqtt_pubrel,52},20 => {mqtt_pubrel,20},50 => {mqtt_pubrel,50},25 => {mqtt_pubrel,25},44 => {mqtt_pubrel,44},36 => {mqtt_pubrel,36},1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}


10:35:23.709 [error] emulator Error in process <0.22974.4> on node 'VerneMQ@127.0.0.1' with exit value:
{[{reason,{case_clause,{vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}
```

last event `connected(#mqtt_pubcomp{message_id=1}, State)`  but `1 = #vmq_msg`
msg `1 => #vmq_msg`   didn't change to  `1 => #mqtt_pubcomp`

**Comment by boboxiaodd** [comment] 2019-01-23 06:03
@dergraf 
when a pubrel is retried after a client reconnects
why  `mqtt_pubrel`  change  to  `vmq_msg`  (`vmq_mqtt_fsm:prepare_frame`)?
if not change this, it work correct
```erlang
10:35:22.881 [info] handle_messages:873 deliver_pubrel waiting_acks:#{1 => {mqtt_pubrel,1}}

10:35:22.882 [info] prepare_frame:918 prepare_frame waiting_acks:#{1 => {vmq_msg,<<154,188,21,166,222,10,84,97,119,130,190,84,62,229,53,120>>,[<<"u_16980398">>,<<"message">>],<<"msg payload">>}}

```

**Comment by larshesel** [comment] 2019-01-23 06:18
I guess what we'd like to understand why the `vmq_msg` got in there in the first place. Can you reproduce this on a clean system with the messagestore wiped? And if so, what are the steps to do so?

**Comment by boboxiaodd** [comment] 2019-01-23 06:50
@larshesel 
i think only this line trigger prepare_frame:
i set `max_inflight_messages=0` 
https://github.com/vernemq/vernemq/blob/fccea67f56f8ae92de9be51f1656923a0cf259fa/apps/vmq_server/src/vmq_mqtt_fsm.erl#L892

**Comment by boboxiaodd** [comment] 2019-01-24 02:47
@dergraf @larshesel 
I think i found the reason:
when a pubrel is retried after a client reconnects,  add    `#{1 => {mqtt_pubrel,1}}`  but not setting 
`State#state.next_msg_id` , 

https://github.com/vernemq/vernemq/blob/fccea67f56f8ae92de9be51f1656923a0cf259fa/apps/vmq_server/src/vmq_mqtt_fsm.erl#L902

so , next msg use  `msg_id = 1`  again ，and will overwrite `#{1 => {mqtt_pubrel,1}}`

**Comment by larshesel** [comment] 2019-01-24 08:07
The increment of the msg_id is done here: https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_mqtt_fsm.erl#L935 so it should not be necessary to increment it again later.

At least it's not clear to me that this why this would fix the root cause as we're not yet even sure what the root cause is. Since you are getting a case clause with `vmq_msg` it seems to me you might have had old messages from an older version in the system? I believe we made a change to how we handle persisted messages a while back, but haven't yet had time to look into that. Did you do an upgrade on said system recently? This is also why I ask if you can reproduce it on a clean system?

**Comment by boboxiaodd** [comment] 2019-01-24 08:18
`get_msg_id()` is return current msg id , and add `next_msg_id `
when `handle_messages deliver_pubrel `  if not modify next_msg_id = 2 , it return 1 

![image](https://user-images.githubusercontent.com/4714247/51664005-4ebc7b80-1ff3-11e9-8f70-89d7336bea99.png)

**Comment by boboxiaodd** [comment] 2019-02-15 02:17
@dergraf @larshesel 
is any plan to fix this issues ?

**Comment by larshesel** [comment] 2019-02-15 06:38
Yes, we plan that it will be part of 1.7.1 which we'll release soon.

**Closed** 2019-02-22 16:57 UTC
