### ISSUE TITLE
The shared subscriptions and session balancing

### ISSUE THREAD

**Issue by onlywangyh** [vernemq/vernemq#937] opened 2018-11-02 03:54 UTC
### Environment

- VerneMQ Version:1.6
- OS:ubuntu16
- Erlang/OTP version (if building from source):21.0

### Expected behavior
balance the share session
- Please describe the expected behaviour.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.
I open the "allow_multiple_session=on", So that i can balance the session. But there is a problems, that i can balance the session only on one node with the same cliend_id. In fact, data from the same topic may be sent to different nodes in the cluster. So i want to subscribe the same topic on diffient node. The shared subscriptions can be used. I also want to balance the share seesion on each node(the topic like "$share/group/mqtt1").
In fact , the balance session is successed. but i can't subscribe the share topic. I don't know if that's feasible. 
My config file:
allow_anonymous = on
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = on
queue_deliver_mode = balance
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 10.118.15.68:44053
listener.http.default = 0.0.0.0:8888
listener.mountpoint = off
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = random
plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = off
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 3
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 3
vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off
log.console = file
log.console.level = debug
log.console.file = /app/vernemq/log/console.log
log.error.file = /app/vernemq/log/error.log
log.syslog = on
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = wyh2@10.118.15.68
distributed_cookie = sf_vmq
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
My acl file ：
#topic sf
user sf001
topic /sf/mqtt1
topic /sf/mqtt2
topic $share#

user sf002
topic #

**Comment by larshesel** [comment] 2018-11-02 07:09
Does this work if you disable the ACL or is the question how to configure ACL?

**Comment by onlywangyh** [comment] 2018-11-02 07:17
Thanks a lot . In fact , I can't receive message from the "$share/sf/mqtt1".  The Shared subscriptions don't appear to work as intended. I don't know how to share the subscriptions. Maybe there is something wrong with my ACL ?

**Comment by larshesel** [comment] 2018-11-02 07:53
Right, so first disable ACLs to make everything simpler and easier to understand. So replace the content of the acl file with `topic #` as it was to begin with.

Then you can start experimenting with shared subscriptions. A common pitfall is to not quote the topic if using cli tools as `$share` will otherwise be interpreted as a environment variable which is empty. 

So if you subscribe like this: `mosquitto_sub -i sub -t '$share/group1/topic' ` (not the quotes around the topic!) then it should work and if you publish to `mosquitto_pub -i pub -t topic -m hello` you will receive the messages. If you then add more subscribers (with different client-ids) then they'll get the messages distributed between them in a random fashion.

**Comment by larshesel** [comment] 2018-11-02 07:57
Notice, as mentioned in the other issue that you can define different policies for your shared subscriptions which is important if you're running a cluster: 

> Currently three message distribution policies for shared subscriptions are supported: prefer_local, random and local_only. Under the random policy messages will be published to a random member of the shared subscription, if any exist. Under the prefer_local policy messages will be delivered to a random node-local member of the shared subscription, if none exist, the message will be delivered to a random member of the shared subscription on a remote cluster node. Under the local_only policy message will be delivered to a random node-local member of the shared subscription.

From https://docs.vernemq.com/configuring-vernemq/shared_subscriptions

**Comment by larshesel** [comment] 2018-11-02 07:57
sorry, closed by mistake

**Comment by onlywangyh** [comment] 2018-11-02 09:52
Thank you very much! successful! The ACL config must add the "topic #" in the first line. By the way, if i use the share subscriptions, it's means that the Session Balancing is useless?

**Comment by larshesel** [comment] 2018-11-02 09:57
Great it works! If by session balancing you mean `allow_multiple_sessions` then yes, you probably don't need that. Shared subscriptions is anyway a standard feature while `allow_multiple_sessions` is not.

**Comment by onlywangyh** [comment] 2018-11-05 10:09
Hi, I have a new problem with Shared subscriptions. When I use the mysql to cache the ACLs. The Shared subscriptions cann't work. I try to add a null user and passwd, to pub and sub topic "#". But it failed. So what kind of data should we add to the tables "vmq_auth_acl"?

**Comment by larshesel** [comment] 2018-11-05 13:33
Which authorization plugin are you using? The diversity plugins doesn't allow users without username and password IIRC.

In any case please explain in detail what you did and what the problem is - it's very hard to give helpful advice without details

**Comment by onlywangyh** [comment] 2018-11-06 03:09
Thanks a lot. We used the following guidelines https://vernemq.com/docs/configuration/db-auth.html. We want to use  MySQL authentication and authorization. It is works, but we can't use the Shared subscriptions anymore. When we use "mosquitto_sub -h localhost -t '$share/sf/mqtt1' -u sf001 -P sf001 -v" to sub this topic '$share/sf/mqtt1' . we can't receive any messages. 
I gusess we have not setting the right  authentication and authorization. When we use files to  authenticate, we need add the "topic #" in first line. This means all users can receive the system topic like '$share/sf/mqtt1' ? 
So we try to insert a piece of data into the table "vmq_auth_acl" which was created in Mysql. This data contains a null mountpoint, null client_id, null username, null password, but the publish_acl and subscribe_acl is " [{"pattern":"#"}] ". This sql is like : " INSERT INTO vmq_auth_acl (mountpoint, client_id, username, password, publish_acl, subscribe_acl) VALUES ('', '', '', '', '[{"pattern":"#"}]', '[{"pattern":"#"}]'); " . But it does not work.

This is the way to setting mysql plugin:
1. setting the vernemq config : 
allow_anonymous = off
plugins.vmq_passwd = off
plugins.vmq_acl = off
allow_multiple_sessions = off

2.setting for mysql:
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.mysql.host = 10.118.15.68
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = sfapp
vmq_diversity.mysql.password = 123456
vmq_diversity.mysql.database = iot

3. create tabls:
CREATE TABLE vmq_auth_acl
(
  mountpoint VARCHAR(10) NOT NULL,
  client_id VARCHAR(128) NOT NULL,
  username VARCHAR(128) NOT NULL,
  password VARCHAR(128),
  publish_acl TEXT,
  subscribe_acl TEXT,
  CONSTRAINT vmq_auth_acl_primary_key PRIMARY KEY (mountpoint, client_id, username)
)

4. Insert datas:
INSERT INTO vmq_auth_acl (mountpoint, client_id, username, password, publish_acl, subscribe_acl) VALUES ('', '', '', '', '[{"pattern":"#"}]', '[{"pattern":"#"}]');

INSERT INTO vmq_auth_acl (mountpoint, client_id, username, password, publish_acl, subscribe_acl) VALUES ('', 'sf001', 'sf001', PASSWORD('123'), '[{"pattern":"mqqtt1"},{"pattern":"mqtt2"}]', '[{"mqtt1"},{"mqtt2"}]');

**Comment by onlywangyh** [comment] 2018-11-06 08:54
Hi, I try to test this function "Shared subscriptions". I find that if we want sub this topic "$share/group1/topicname", we need to add appropriate authority management.  Thanks a lot .

**Comment by larshesel** [comment] 2018-11-22 06:31
> null mountpoint, null client_id, null username, null password,

This data needs to be concrete - with the out-of-the-box lua script for mysql 'wildcard'-users are not supported. Every user accessing the broker need to be fully specified in the database.

**Closed by larshesel** 2018-11-22 06:31 UTC
