### ISSUE TITLE
Cuttlefish chokes on lines with only whitespace characters in the config file

### ISSUE THREAD

**Issue by puresilk** [vernemq/vernemq#1208] opened 2019-06-04 22:01 UTC
See 
https://pi3g.com/2019/06/04/debugging-vernemq-connection-authentication-problems-for-dual-authentication-with-webhooks-and-vmq_diversity/ (Bonus section)

The problem is that cuttlefish chokes on lines which have only whitespace characters (e.g. tabs) in the config file. This is a particularly difficult issue to debug, as you literally can't see the whitespace. (nano will turn it on if you press Alt + P). 

This is what we get currently:
```
jalpine_morpheus | Error generating config with cuttlefish
jalpine_morpheus |   run `vernemq config generate -l debug` for more information.
```
and when drilling down with ```vernemq config generate -l debug```:

```
jalpine_morpheus | escript: exception error: no function clause matching
jalpine_morpheus |                  lists:unzip([[ws,ws],
jalpine_morpheus |                               {["log","console","file"],"./log/console.log"},
jalpine_morpheus |                               {["log","error","file"],"./log/error.log"},
jalpine_morpheus |                               {["log","syslog"],"off"},
jalpine_morpheus |                               {["log","crash"],"on"},
jalpine_morpheus |                               {["log","crash","file"],"./log/crash.log"},
jalpine_morpheus |                               {["log","crash","maximum_message_size"],"64KB"},
jalpine_morpheus |                               {["log","crash","size"],"10MB"},
jalpine_morpheus |                               {["log","crash","rotation"],"$D0"},
jalpine_morpheus |                               {["log","crash","rotation","keep"],"5"},
jalpine_morpheus |                               {["nodename"],"VerneMQ@127.0.0.1"},
jalpine_morpheus |                               {["distributed_cookie"],"vmq"},
jalpine_morpheus |                               {["erlang","async_threads"],"64"},
jalpine_morpheus |                               {["erlang","max_ports"],"262144"},
jalpine_morpheus |                               {["leveldb","maximum_memory","percent"],"70"},
(snip)
jalpine_morpheus |                               {["log","console"],"console"},
jalpine_morpheus |                               {["erlang","distribution","port_range",
jalpine_morpheus |                                 "minimum"],
jalpine_morpheus |                                "9100"},
jalpine_morpheus |                               {["erlang","distribution","port_range",
jalpine_morpheus |                                 "maximum"],
jalpine_morpheus |                                "9109"}],
jalpine_morpheus |                              [["log","console","level"],
jalpine_morpheus |                               ["log","console"],
jalpine_morpheus |                               ["vmq_diversity","auth_redis","enabled"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","database"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","password"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","login"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","port"],
jalpine_morpheus |                               ["vmq_diversity","mongodb","host"],
jalpine_morpheus |                               ["vmq_diversity","auth_mongodb","enabled"],
jalpine_morpheus |                               ["vmq_diversity","mysql","password_hash_method"],
jalpine_morpheus |                               ["vmq_diversity","auth_mysql","enabled"],
jalpine_morpheus |                               ["vmq_diversity","auth_postgres","enabled"],
jalpine_morpheus |                               ["vmq_diversity","script_dir"],
jalpine_morpheus |                               ["vmq_passwd","password_reload_interval"],
jalpine_morpheus |                               ["vmq_passwd","password_file"],
jalpine_morpheus |                               ["vmq_acl","acl_reload_interval"],
jalpine_morpheus |                               ["vmq_acl","acl_file"],
jalpine_morpheus |                               ["metadata_plugin"],
jalpine_morpheus |                               ["plugins","vmq_bridge"],
jalpine_morpheus |                               ["plugins","vmq_webhooks"],
jalpine_morpheus |                               ["plugins","vmq_diversity"],
jalpine_morpheus |                               ["plugins","vmq_acl"],
jalpine_morpheus |                               ["plugins","vmq_passwd"],
jalpine_morpheus |                               ["shared_subscription_policy"],
jalpine_morpheus |                               ["graphite_interval"],
jalpine_morpheus |                               ["graphite_port"],
jalpine_morpheus |                               ["graphite_host"],
jalpine_morpheus |                               ["graphite_enabled"],
jalpine_morpheus |                               ["systree_interval"],
jalpine_morpheus |                               ["systree_enabled"],
jalpine_morpheus |                               ["listener","ws","piclient","mountpoint"],
jalpine_morpheus |                               ["listener","ws","jsclient","mountpoint"],
jalpine_morpheus |                               ["listener","ws","piclient"],
jalpine_morpheus |                               ["listener","ws","jsclient"],
jalpine_morpheus |                               ["listener","nr_of_acceptors"],
jalpine_morpheus |                               ["listener","max_connections"],
jalpine_morpheus |                               ["upgrade_outgoing_qos"],
jalpine_morpheus |                               ["max_message_size"],
jalpine_morpheus |                               ["max_offline_messages"],
jalpine_morpheus |                               ["max_online_messages"],
jalpine_morpheus |                               ["max_inflight_messages"],
jalpine_morpheus |                               ["allow_multiple_sessions"],
jalpine_morpheus |                               ["allow_unsubscribe_during_netsplit"],
jalpine_morpheus |                               ["allow_subscribe_during_netsplit"],
jalpine_morpheus |                               ["allow_publish_during_netsplit"],
jalpine_morpheus |                               [[...]],
jalpine_morpheus |                               [...]],
jalpine_morpheus |                               [...]|...]) (lists.erl, line 402)
jalpine_morpheus |   in function  cuttlefish_conf:file/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_conf.erl, line 74)
jalpine_morpheus |   in call from cuttlefish_conf:'-files/1-fun-1-'/2 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_conf.erl, line 45)
jalpine_morpheus |   in call from lists:foldl/3 (lists.erl, line 1263)
jalpine_morpheus |   in call from cuttlefish_conf:files/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_conf.erl, line 43)
jalpine_morpheus |   in call from cuttlefish_escript:load_conf/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_escript.erl, line 307)
jalpine_morpheus |   in call from cuttlefish_escript:engage_cuttlefish/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_escript.erl, line 361)
jalpine_morpheus |   in call from cuttlefish_escript:generate/1 (/vernemq-build/_build/default/lib/cuttlefish/src/cuttlefish_escript.erl, line 255)
```

I feel that a warning could be either a bit more explicit, stating that possibly whitespace is the problem, or whitespace should be accepted (an even more preferred solution - why does the whitespace matter?)

I ran into this issue while debugging with VerneMQ for a different issue, and having edited the config file with nano. 
I have VerneMQ version 1.7.1 - not tested with 1.8.0, but I had a look at the changelog and did not see it. I will upgrade to VerneMQ 1.8.0 in the near time, and might be able to test it.

**Comment by larshesel** [comment] 2019-06-05 06:41
Hi,

Thanks for the report. I just tried to add a line in my vernemq.conf file with just a tab + newline and this didn't seem to be a problem. Neither was a line with a bunch of spaces + newline. I tried both a tab and spaces at the end of the file (without newline) which also didn't pose a problem. This was with VerneMQ 1.8.0 - but I don't think we've upgraded cuttlefish for quite a while so I'd expect it to be the same in 1.7.x. So I'm not able to reproduce this so obviously I'm doing something differently, but what?

Thanks for the writeup about lua - we'll take a look at improving the docs!

**Comment by puresilk** [comment] 2019-06-05 20:43
Hi,

my pleasure. I am very happy that this works - now I can implement the auth. Looking forward to VerneMQ v2.0 very much, where independent plugin chains per listener will be possible, right? 

I have now upgrade VerneMQ to 1.8.0:
image: erlio/docker-vernemq:1.8.0-alpine

and can reproduce the error. 

**Sidenote: can I reuse the 1.7.2 conf file without problems for 1.8.0, or are there things and new settings I should be aware of, and take care of by adjusting a fresh config file?**

Instructions for reproduction of the error:

Open vernemq.conf.local, go to the first blank line. 
This happens tobe right after 
```allow_anonymous = off```
for me. 
Insert **two tabs** (tab key twice). 
Save the file, try to start VerneMQ.

![image](https://user-images.githubusercontent.com/4606111/58988578-4f0b2580-87e2-11e9-8a52-2ff092858c26.png)

showing whitespace characters with nano (Alt+P):
![image](https://user-images.githubusercontent.com/4606111/58988649-6813d680-87e2-11e9-9d34-cdaeded00b71.png)
The dots indicate a space, the angle brackets a tab.

I can attach an edited version of my config file, or send it to you privately without editing, so you can reproduce? Please advise if this is required.

Max

**Comment by larshesel** [comment] 2019-06-06 06:18
I can confirm this - I should take more care when testing this out - I have my env set up to strip white-space at the end of lines but switching that off and inserting tabs made it work - or rather not work as I then get the error you outline.

We'd have to look into how we can best fix this as this is as you already mention a bug in cuttlefish, not VerneMQ itself, perhaps it would be best to create an issue there?

**Comment by puresilk** [comment] 2019-06-06 10:46
I agree that the proper place is cuttlefish for this issue. 
Is this the correct repository for cuttlefish?
https://github.com/basho/cuttlefish/issues/246

The issue is asking whether this repository is deprecated.

I have had a rough look at the open and closed issues, and did not see something relating to this whitespace issue. 

Would you like me to open an issue with cuttlefish, referring back to this issue?

**Comment by codeadict** [comment] 2019-07-16 19:46
The repository used in VerneMQ is actually https://github.com/Kyorai/cuttlefish, they have released quite a bit since the pinned version we have, now RabbitMQ migrated to cuttlefish and is contributing a bit to that repo. This is also the version published to hex.pm and they had a release 5 days ago, so will be good to make an update. I'll submit a pr.

**Comment by larshesel** [comment] 2019-07-29 11:46
hi @puresilk, could you open an issue over at https://github.com/Kyorai/cuttlefish? Then we'd upgrade to the latest version when it's been fixed.

**Comment by puresilk** [comment] 2019-07-31 13:52
@larshesel I have added the issue to  the Kyorai cuttlefish repo

https://github.com/Kyorai/cuttlefish/issues/1

Do you off the top of your head know the version of cuttlefish used, so I could put it into the report? Otherwise I will try to look in the repo, which version is used in VerneMQ 1.8.0 (the version I tested with).

**Comment by larshesel** [comment] 2019-07-31 15:04
Hey, cool! Yes, we used cuttlefish 2.2.0 (https://hex.pm/packages/cuttlefish/2.2.0)

**Comment by michaelklishin** [comment] 2019-08-03 07:12
Should be addressed in https://github.com/Kyorai/cuttlefish/pull/2.

**Comment by larshesel** [comment] 2019-08-05 08:37
Thanks @michaelklishin I've updated to the latest commit on the `develop` branch and this solves the issue.

**Closed** 2019-08-07 12:25 UTC
Labels: bug, cuttlefish
