### ISSUE TITLE
Stuck session is preventing client re-connect

### ISSUE THREAD

**Issue by chriswue** [vernemq/vernemq#893] opened 2018-10-12 01:24 UTC
### Environment

- VerneMQ Version: 1.5.0
- OS: official docker image running on Ubuntu 18.04

On one of our brokers we've observed a stuck client session. The client publishes ~5,500 messages/sec on an ongoing basis. After around 60h of continuous running the client got disconnected by the broker and hasn't been able to reconnect.

When that particular client tries to connect, this is what gets logged:

    [warning] can't register client {[],<<"the-client-id">>} due to reason action_timeout

Other clients can still connect fine - it's just this particular client id.

Before the timeout was hit the following message was logged regularly as well:

    [info] monitor busy_port <0.515.0> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,1}] #Port<0.11015>

with the `message_queue_len` varying between 0 and 2

That client doesn't appear in the `vmq-admin session show` command.
`vmq-admin trace client` output:

    Starting trace for 1 existing sessions for client "the-client-id" with PIDs
    [<7251.14618.0>]
    New session with PID <7251.20870.2> found for client "the-client-id"
    <7251.20870.2> MQTT RECV: CID: "the-client-id" CONNECT(c: the-client-id, v: 4, u: undefined, p: undefined, cs: 0, ka: 60)
    New session with PID <7251.20880.2> found for client "the-client-idr"
    <7251.20880.2> MQTT RECV: CID: "the-client-id" CONNECT(c: the-client-id, v: 4, u: undefined, p: undefined, cs: 0, ka: 60)

I can run `vmq-admin session disconnect` on the client which reports Ok but it doesn't change anything or create any log entries.

VerneMQ is currently using around 2GB RAM - the online message queue size is 10,000. LevelDB backend is disabled

Is there anything else I can do to debug this?

**Comment by chriswue** [comment] 2018-10-14 22:51
4 connected clients - 3 publishers (only one pushing hard) and one subscriber subscribing to all topics being published

**Comment by dergraf** [comment] 2018-10-15 17:46
is the client reconnecting to the same cluster node or a different node?

**Comment by chriswue** [comment] 2018-10-15 18:55
There is no cluster, just a single instance so it's always the same node.

**Comment by chriswue** [comment] 2018-10-19 04:51
As an additional data point - I've set the max_online_messages to be 100,000 and max_offline_messages to 1,000,000 (LevelDB backend is enabled). I restarted the broker after experimenting around with subscribers going offline and see how the broker behaves regarding memory consumption etc. On restart it spent a lot of time on disk I/O presumably scanning the disk queues but now none of the clients can connect. They all fail with:

    can't register client {[],<<"some-client-id">>} due to reason action_timeout

Subsequent broker restarts happen faster with a lot less disk I/O but all clients time out with the above error. So this is a pretty reliable way to brick the broker install. The only way to get it going again is to completely remove the docker container and re-create it.

**Comment by ioolkos** [comment] 2018-10-19 08:52
Ok, let's suppose we fill up a queue with 1Million offline messages. Those go into LevelDB too. Then we restart the broker. Then we reconnect the consumer for those messages (clean session = false, so it will resume it's session).

@dergraf, @larshesel the delay can't be caused by the merkle tree build-up, can't it? (because we only have a few session). But spawning the queue, and then filling it up with 1Million messages (copying from LevelDB to RAM), that could take some time, right? Then we might have a session trying to attach to a somewhat blocked queue, or something like that.

**Comment by dergraf** [comment] 2018-10-19 17:33
initially the offline queue should be compacted, only keeping refs to the message instead of the whole message containing payload... 
however a lot of initialization is going on during boot, and it can consume quite a bit of CPU/RAM, during that time it's definitely possible to run into action_timeout errors. 

I think it would be interesting to know the number of metadata tombstones in the system as those are to my knowledge the only reason why the system won't come back to a stable state on time. 

For further investigations we'd need a CPU/Memory profile as well as a description of all events that brought VerneMQ into this state.

**Comment by chriswue** [comment] 2018-10-23 21:40
As I stated - on the first broker restart it does indeed take a long time and spends a lot of disk-I/O and during that time VerneMQ will reject all incoming connections (not a timeout just plain reject the connection). Once the disk-I/O has all died down then VerneMQ starts accepting incoming connections in principle but they all timeout with the stated error.

Subsequent broker restart are a lot faster and consume a lot less disk-I/O but still incoming connections time out (for clean session = false).

I'll try and see if I can create a minimal reproducible test case.

**Comment by larshesel** [comment] 2018-12-11 07:51
Hi, were you able to create a test case reproducing this? I'll close it for now, but please let us know if more information becomes available!

**Closed by larshesel** 2018-12-11 07:51 UTC

**Comment by chriswue** [comment] 2018-12-19 00:08
@larshesel No, haven't managed to find a reproducible test setup for this. We've now moved to use mosquitto so won't be able to investigate this for some time
