### ISSUE TITLE
Vernemq crashed due to bad argument

### ISSUE THREAD

**Issue by chenxinlong** [vernemq/vernemq#938] opened 2018-11-02 06:04 UTC
### Environment

- VerneMQ Version: 1.5.0
- OS:centos 7
- Erlang/OTP version (if building from source):

### Relevant logs

console.log
```
...
====there's no errors before this line ==========
2018-11-02 02:49:26.176 [debug] <0.17872.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:49:27.989 [debug] <0.260.0>@plumtree_broadcast:exchange:500 started plumtree_metadata_manager exchange with 'VerneMQ@xx.xx.xx.xx' (<0.17937.1>)
2018-11-02 02:49:31.149 [debug] <0.260.0>@plumtree_broadcast:schedule_lazy_tick:700 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
2018-11-02 02:49:37.990 [debug] <0.260.0>@plumtree_broadcast:exchange:500 started plumtree_metadata_manager exchange with 'VerneMQ@xx.xx.xx.xx' (<0.17942.1>)
2018-11-02 02:49:40.283 [warning] <0.17944.1>@vmq_mqtt_fsm:check_user:557 can't authenticate client {[],<<"444ce89317648e5f5a958e24da9a455b">>} due to error
2018-11-02 02:49:40.283 [debug] <0.17944.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:49:40.404 [debug] <0.17945.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:49:41.150 [debug] <0.260.0>@plumtree_broadcast:schedule_lazy_tick:700 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
2018-11-02 02:49:47.991 [debug] <0.260.0>@plumtree_broadcast:exchange:500 started plumtree_metadata_manager exchange with 'VerneMQ@xx.xx.xx.xx' (<0.17948.1>)
2018-11-02 02:49:51.151 [debug] <0.260.0>@plumtree_broadcast:schedule_lazy_tick:700 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
2018-11-02 02:49:57.992 [debug] <0.260.0>@plumtree_broadcast:exchange:500 started plumtree_metadata_manager exchange with 'VerneMQ@xxx.xx.xx.xx' (<0.17952.1>)
2018-11-02 02:50:01.152 [debug] <0.260.0>@plumtree_broadcast:schedule_lazy_tick:700 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
2018-11-02 02:50:02.637 [debug] <0.17960.1>@vmq_queue:state_change:948 transition from offline --> online because of add_session
2018-11-02 02:50:02.797 [debug] <0.17957.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:50:05.656 [debug] <0.17964.1>@vmq_queue:state_change:948 transition from offline --> online because of add_session
2018-11-02 02:50:07.993 [debug] <0.260.0>@plumtree_broadcast:exchange:500 started plumtree_metadata_manager exchange with 'VerneMQ@xxx.xx.xx.xx' (<0.17967.1>)
2018-11-02 02:50:09.166 [debug] <0.17961.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:50:10.283 [warning] <0.17979.1>@vmq_mqtt_fsm:check_user:557 can't authenticate client {[],<<"444ce89317648e5f5a958e24da9a455b">>} due to error
2018-11-02 02:50:10.283 [debug] <0.17979.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:50:10.354 [debug] <0.17982.1>@vmq_queue:state_change:948 transition from offline --> online because of add_session
2018-11-02 02:50:10.376 [debug] <0.17983.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:50:10.514 [debug] <0.17986.1>@vmq_queue:state_change:948 transition from offline --> online because of add_session
2018-11-02 02:50:11.153 [debug] <0.260.0>@plumtree_broadcast:schedule_lazy_tick:700 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
2018-11-02 02:50:16.013 [error] <0.13558.0> CRASH REPORT Process <0.13558.0> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_status, ready) in vmq_cluster:is_ready/0 line 69
2018-11-02 02:50:16.014 [error] <0.13558.0> Ranch listener {{xxx.xx.xx.xxx},1883} terminated with reason: badarg
2018-11-02 02:50:16.016 [debug] <0.17978.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:50:16.016 [debug] <0.17977.1>@vmq_ranch:teardown:134 session normally stopped
2018-11-02 02:50:16.017 [error] <0.17386.1> CRASH REPORT Process <0.17386.1> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_status, ready) in vmq_cluster:is_ready/0 line 69
2018-11-02 02:50:16.018 [error] <0.17386.1> Ranch listener {{xxx.xxx.xxx.xxx},1883} terminated with reason: badarg
2018-11-02 02:50:16.021 [error] <0.20309.0> CRASH REPORT Process <0.20309.0> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_status, ready) in vmq_cluster:is_ready/0 line 69
2018-11-02 02:50:16.022 [error] <0.20309.0> Ranch listener {{xxx.xxx.xx.xxx},1883} terminated with reason: badarg
2018-11-02 02:56:30.218 [debug] <0.195.0>@lager_handler_watcher:119 Lager installed handler {lager_file_backend,"/var/log/vernemq/error.log"} into lager_event
2018-11-02 02:56:30.218 [debug] <0.197.0>@lager_handler_watcher:119 Lager installed handler error_logger_lager_h into error_logger
2018-11-02 02:56:30.276 [debug] <0.117.0> Supervisor gr_param_sup started gr_param:start_link(gr_lager_default_tracer_params) at pid <0.199.0>
2018-11-02 02:56:30.276 [debug] <0.116.0> Supervisor gr_counter_sup started gr_counter:start_link(gr_lager_default_tracer_counters) at pid <0.200.0>
```

crash.log
```
2018-11-02 02:50:16 =CRASH REPORT====
  crasher:
    initial call: vmq_ranch:init/5
    pid: <0.13558.0>
    registered_name: []
    exception error: bad argument: [{ets,lookup,[vmq_status,ready],[]},{vmq_cluster,is_ready,0,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_cluster.erl"},{line,69}]},{vmq_reg,publish,3,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,283}]},{vmq_mqtt_fsm,maybe_publish_last_will,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,934}]},{vmq_mqtt_fsm,terminate,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,468}]},{vmq_mqtt_fsm,in,3,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,173}]},{vmq_mqtt_fsm,msg_in,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,161}]},{vmq_ranch,handle_message,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,234}]}]
    ancestors: [<0.1551.0>,<0.1550.0>,ranch_sup,<0.64.0>]
    messages: []
    links: [<0.1551.0>,#Port<0.14299>]
    dictionary: [{mqtt_publish_sent,<<>>},{mqtt_pubcomp_sent,<<>>},{mqtt_pubcomp_received,<<>>},{mqtt_suback_sent,<<>>},{mqtt_subscribe_received,<<>>},{bytes_sent,<<>>},{rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,type => exsplus,uniform => #Fun<rand.9.41921595>,uniform_n => #Fun<rand.10.41921595>},[71778646232498481|219813150733517522]}},{bytes_received,<<>>},{guid,{{'VerneMQ@xxx.xxx.xxx.xx',<0.13558.0>,{1541,58909,469870}},26}},{mqtt_pingreq_received,<<>>},{mqtt_pingresp_sent,<<>>},{socket_open,<<>>},{max_msg_size,0},{mqtt_pubrec_received,<<>>},{mqtt_pubrel_received,<<>>},{mqtt_pubrec_sent,<<>>},{mqtt_connect_received,<<>>},{mqtt_publish_received,<<>>},{mqtt_connack_accepted_sent,<<>>},{mqtt_pubrel_sent,<<>>}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 70056
  neighbours:
2018-11-02 02:50:16 =ERROR REPORT====
Ranch listener {{xxx,xx,xxx,xxx},1883} had connection process started with vmq_ranch:start_link/4 at <0.13558.0> exit with reason: badarg
2018-11-02 02:50:16 =CRASH REPORT====
  crasher:
    initial call: vmq_ranch:init/5
    pid: <0.17386.1>
    registered_name: []
    exception error: bad argument: [{ets,lookup,[vmq_status,ready],[]},{vmq_cluster,is_ready,0,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_cluster.erl"},{line,69}]},{vmq_reg,publish,3,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,283}]},{vmq_mqtt_fsm,maybe_publish_last_will,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,934}]},{vmq_mqtt_fsm,terminate,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,468}]},{vmq_mqtt_fsm,in,3,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,173}]},{vmq_mqtt_fsm,msg_in,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,161}]},{vmq_ranch,handle_message,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,234}]}]
    ancestors: [<0.1551.0>,<0.1550.0>,ranch_sup,<0.64.0>]
    messages: []
    links: [<0.1551.0>,#Port<0.17671>]
    dictionary: [{mqtt_pubcomp_received,<<>>},{mqtt_suback_sent,<<>>},{mqtt_subscribe_received,<<>>},{bytes_sent,<<>>},{rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,type => exsplus,uniform => #Fun<rand.9.41921595>,uniform_n => #Fun<rand.10.41921595>},[71504378214939810|72309850724249091]}},{bytes_received,<<>>},{mqtt_publish_sent,<<>>},{mqtt_pubcomp_sent,<<>>},{guid,{{'VerneMQ@xxx.xxx.xx.xx',<0.17386.1>,{1541,126094,298137}},107}},{mqtt_pingreq_received,<<>>},{mqtt_pingresp_sent,<<>>},{socket_open,<<>>},{max_msg_size,0},{mqtt_pubrec_received,<<>>},{mqtt_pubrec_sent,<<>>},{mqtt_pubrel_received,<<>>},{mqtt_connect_received,<<>>},{mqtt_publish_received,<<>>},{mqtt_connack_accepted_sent,<<>>},{mqtt_pubrel_sent,<<>>}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 83454
  neighbours:
2018-11-02 02:50:16 =ERROR REPORT====
Ranch listener {{xxx,xx,xxx,xx},1883} had connection process started with vmq_ranch:start_link/4 at <0.17386.1> exit with reason: badarg
2018-11-02 02:50:16 =CRASH REPORT====
  crasher:
    initial call: vmq_ranch:init/5
    pid: <0.20309.0>
    registered_name: []
    exception error: bad argument: [{ets,lookup,[vmq_status,ready],[]},{vmq_cluster,is_ready,0,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_cluster.erl"},{line,69}]},{vmq_reg,publish,3,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,283}]},{vmq_mqtt_fsm,maybe_publish_last_will,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,934}]},{vmq_mqtt_fsm,terminate,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,468}]},{vmq_mqtt_fsm,in,3,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,173}]},{vmq_mqtt_fsm,msg_in,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,161}]},{vmq_ranch,handle_message,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,234}]}]
    ancestors: [<0.1551.0>,<0.1550.0>,ranch_sup,<0.64.0>]
    messages: []
    links: [<0.1551.0>,#Port<0.15385>]
    dictionary: [{socket_open,<<>>},{max_msg_size,0},{mqtt_pubrec_sent,<<>>},{guid,{{'VerneMQ@xxx.xx.xx.xxx',<0.20309.0>,{1541,69357,479993}},1}},{mqtt_connack_accepted_sent,<<>>},{bytes_sent,<<>>},{mqtt_publish_received,<<>>},{mqtt_connect_received,<<>>},{bytes_received,<<>>},{rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,type => exsplus,uniform => #Fun<rand.9.41921595>,uniform_n => #Fun<rand.10.41921595>},[71752738993284405|219954603907603993]}},{mqtt_pubrel_received,<<>>},{mqtt_pubcomp_sent,<<>>},{mqtt_pingreq_received,<<>>},{mqtt_pingresp_sent,<<>>}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 44239
  neighbours:
2018-11-02 02:50:16 =ERROR REPORT====
Ranch listener {{xxx,xxx,xx,xx},1883} had connection process started with vmq_ranch:start_link/4 at <0.20309.0> exit with reason: badarg

```

error.log
```
2018-11-02 02:50:16.013 [error] <0.13558.0> CRASH REPORT Process <0.13558.0> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_status, ready) in vmq_cluster:is_ready/0 line 69
2018-11-02 02:50:16.014 [error] <0.13558.0> Ranch listener {{xx,xx,xx,xx},1883} terminated with reason: badarg
2018-11-02 02:50:16.017 [error] <0.17386.1> CRASH REPORT Process <0.17386.1> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_status, ready) in vmq_cluster:is_ready/0 line 69
2018-11-02 02:50:16.018 [error] <0.17386.1> Ranch listener {{xx,xx,xx,xx},1883} terminated with reason: badarg
2018-11-02 02:50:16.021 [error] <0.20309.0> CRASH REPORT Process <0.20309.0> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_status, ready) in vmq_cluster:is_ready/0 line 69
2018-11-02 02:50:16.022 [error] <0.20309.0> Ranch listener {{xx,xx,xx,xx},1883} terminated with reason: badarg
2018-11-02 02:56:45.348 [error] <0.686.0>@vmq_metrics:incr_item:259 invalid counter queue_setup
2018-11-02 02:56:45.350 [error] <0.688.0>@vmq_metrics:incr_item:259 invalid counter queue_setup
2018-11-02 02:56:45.353 [error] <0.690.0>@vmq_metrics:incr_item:259 invalid counter queue_setup
2018-11-02 02:56:45.355 [error] <0.692.0>@vmq_metrics:incr_item:259 invalid counter queue_setup
2018-11-02 02:56:45.356 [error] <0.694.0>@vmq_metrics:incr_item:259 invalid counter queue_setup
2018-11-02 02:56:45.358 [error] <0.696.0>@vmq_metrics:incr_item:259 invalid counter queue_setup
2018-11-02 02:56:45.363 [error] <0.698.0>@vmq_metrics:incr_item:259 invalid counter queue_setup
2018-11-02 02:56:45.365 [error] <0.700.0>@vmq_metrics:incr_item:259 invalid counter queue_setup

```
### Actual behaviour

It dosen't reproduce frequently. But when one of my cluster node down, other node reset the connection by peer.

**Comment by larshesel** [comment] 2018-11-02 07:04
Hi, thank you for the report. Do you see any errors before these?

> It dosen't reproduce frequently. But when one of my cluster node down, other node reset the connection by peer.

This could be due to the netsplit settings (allow_xxx_during_netsplit), see https://docs.vernemq.com/vernemq-clustering/netsplits

**Comment by chenxinlong** [comment] 2018-11-02 07:39
Sorry I can understand only a fraction of these log. So I've reedit this issue and put more log content in it. Hope it helps.

**Comment by larshesel** [comment] 2018-11-02 08:00
Ok, from the logs I don't really see what the problem is, I'm afraid.

All nodes which have detected the netsplit will stop serving clients (based  on the netsplit settings of course).

Above you write VerneMQ version is 1.15.0 - I suppose you mean 1.5.0?

What plugins do you have enabled? What does the OS metrics (memory/cpu/disk usage) look like when this problem occurs?

**Comment by chenxinlong** [comment] 2018-11-02 08:13
Yes, it's 1.5.0. Sorry for the typo.   

I've enabled these plugin like pics below :    
![image](https://user-images.githubusercontent.com/9261954/47900735-ec9f1f00-deb8-11e8-9a1f-07c502ecd1af.png) 

I didn't check the OS metrics at that time because it restarted when I know VerneMQ crashed.

**Comment by larshesel** [comment] 2018-11-21 06:13
I have no clue what the problem here could be. Without more information I don't think I can do anything - if it happens again the metrics over time as well as the cpu load/memory usage would likely be helpful. Would you be able to upgrade to 1.6.1 - there we have tried to improve the error messages for the `vmq_diversity` plugin as well as  a lot of bugfixes since 1.5.0.

Closing this for now but feel free to repoen if new information comes along.

**Closed by larshesel** 2018-11-21 06:13 UTC
