### ISSUE TITLE
no function clause matching vmq_diversity_script_state:handle_info (v1.7.1)

### ISSUE THREAD

**Issue by ramikushnir** [vernemq/vernemq#1159] opened 2019-04-30 16:14 UTC
### To help us save time and help you faster

Note: this issue has some similarities to #798 (Timeout error for call into Lua sandbox)

### Environment

- VerneMQ Version: 1.7.1
- OS: Alpine Linux 3.9.3 
- VerneMQ configuration:
leveldb.maximum_memory.percent=20
erlang.distribution.port_range.minimum=9100
listener.ssl.default=0.0.0.0:8883
log.console.level=info
persistent_client_expiration=3d
listener.ssl.keyfile=/etc/ssl/myfile.key
listener.ssl.cafile=/etc/ssl/myfile.crt
listener.ssl.require_certificate=off
allow_subscribe_during_netsplit=on
listener.ssl.certfile=/etc/ssl/myfile.crt
allow_publish_during_netsplit=on
erlang.distribution.port_range.maximum=9109
listener.ssl.tls_version=tlsv1.2
listener.vmq.clustering=0.0.0.0:44053
allow_unsubscribe_during_netsplit=on
listener.ssl.depth=5
log.console=console
allow_register_during_netsplit=on
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = x.x.x.x:1883
listener.ws.default =  x.x.x.x:8080
listener.vmq.clustering =  x.x.x.x:44053
listener.http.metrics =  x.x.x.x:8888
- Cluster size/standalone:
3 node cluster
### Expected behavior

Expecting pub/sub normal behavior with authentication via HTTP calls using Lua plugin

### Actual behavior

I'm running some publish/subscribe tests of various scenarios. All connections are done over TLS through port 8883.
No load is applied to the broker. The traffic during the test is about 1 Register, and then Subscribe or Publish and disconnect per second.
At some point I'm seeing a crash report and a massive log output indicating the following: 
```
vmq_diversity_script_state:handle_info:162 gen_server <0.456.0> terminated with reason: no function clause matching vmq_diversity_script_state:handle_info ... 
```
After that, the node continuously prints this kind of messages:
```
2019-04-30 13:51:11.004 [error] <0.3479.0>@vmq_mqtt_fsm:check_user:554 can't authenticate client {[],<<"my-client-id">>} from  x.x.x.x:42358 due to no_matching_hook_found
```
Important notes:
1. The broker authenticates all register/publish/subscribe requests using an HTTP call.
2. This behavior started after upgrading from 1.6.1 to 1.7.1. I haven't seen this behavior in the previous versions. Along with the version upgrade, I have added a substantial amount of applicative logs in the Lua plugin. Can that addition lead to this issue?

**Comment by larshesel** [comment] 2019-05-02 10:59
Hi,

Can you provide log files from when the error first occurs? It also looks like you're using a custom lua script, can you provide this as well?

**Comment by ramikushnir** [comment] 2019-05-05 07:40
@larshesel - Attached.
Thank you!
[vernemq-ticket-1159-A.zip](https://github.com/vernemq/vernemq/files/3145249/vernemq-ticket-1159-A.zip)

**Comment by ioolkos** [comment] 2019-05-05 07:56
@ramikushnir thanks for the additional info.
From what you mentioned the issue is seen with release 1.7.1 and and a new version of you Lua auth script. It worked with Verne release 1.6.1 and and old version of your Lua script.

Now the obvious quick question: do things work with Verne 1.7.1 and your old version of the script?
This would at least narrow things down. (it could be that the additional work in the script leads to timeouts somewhere, or something like that. just conjectures...)

**Comment by ramikushnir** [comment] 2019-05-05 08:21
@ioolkos Thanks for the reply.
Yes, I ran the old lua script on vernemq v1.7.1 and it showed the same symptoms - broker node crashes with the same `no function clause matching vmq_diversity_script_state:handle_info` error and following that, the node stops authenticating clients with `no_matching_hook_found` error printed.

**Comment by ioolkos** [comment] 2019-05-05 08:50
Ok, I guess that narrows things down to changes in `vmq_diversity` between 1.6.1 and 1.7.1, am I right @larshesel?

**Comment by ramikushnir** [comment] 2019-05-05 12:55
@ioolkos , @larshesel please hold the Lua code drill down. I just realized there were changes in the Dockerfile and build process between the versions we deployed that may have caused this issue. Checking.

**Comment by ramikushnir** [comment] 2019-05-06 06:15
@ioolkos Update: 
We're using a docker based deployment.
Up until my last upgrade attempt (when we were using vmq-1.6.1), I was using the Dockerfile shown here: 
https://github.com/vernemq/docker-vernemq/blob/d1e168be8dd0c600744a880977f05b79c9a2a1e3/Dockerfile 
(that's the previous version that used a downloaded .deb file for vmq 1.6.1).
Ever since we started using one of these Dockerfiles: 
https://github.com/vernemq/docker-vernemq/blob/master/Dockerfile or 
https://github.com/vernemq/docker-vernemq/blob/master/Dockerfile.alpine , I started seeing the issue. Including when setting `VERNEMQ_GIT_REF` to `1.6.1`, `1.6.2` and `1.7.1` (i.e. building previous versions). the issue probably has to do with infrastructure changes, lua, erlang or other versions, and not code changed in the lua plugin or, in my opinion, diversity plugin since this is occurring with 1.6.1 and the new Dockerfile.

Any suggestions?

**Comment by ramikushnir** [comment] 2019-05-08 07:24
@ioolkos Did you have a chance to look at my last comment?

**Comment by ioolkos** [comment] 2019-05-08 07:49
So, in short: "old" Dockerfile works, "new" Dockerfile doesn't.

Hm... pinging @larshesel for help here.

**Comment by larshesel** [comment] 2019-05-13 14:25
Hi @ramikushnir I was looking a bit at the logs and the lua code, but I don't see why the dockerfile would play a role here. As far as I can tell the error has something to do with an SSL connection closing. Do you use https from the lua script? Have you found any more clues?

**Comment by ramikushnir** [comment] 2019-05-14 07:05
@larshesel thank you for your answer. Yes, I am using HTTPs from the lua script on every register/pub/sub. I'm still looking into this, trying to narrow down the issue.

**Comment by ramikushnir** [comment] 2019-05-14 09:28
@larshesel Update: I've found the point causing this issue:
When we are making an HTTP call from within the lua script, whenever a `Connection: close`  response header is returned from the server, the MQTT node crashes. 
Usually, the server we are calling is returning a `Connection: keep-alive` header, but at some occasions, which currently I am not sure how they are decided, it returns a `Connection: close` header, and that's when the vernemq node crashes. Our HTTP server's behavior hasn't changed. However, building vernemq using the new Dockerfiles, which introduces infrastructure changes result in this issue.

**Comment by larshesel** [comment] 2019-05-14 09:32
ok - I'll look into if we can handle these errors better - though it doesn't make sense to me that changing the dockerfile can make the remote end close the connection. I think the dockerfile changes is not the root cause.

**Comment by larshesel** [comment] 2019-05-14 11:03
I think the `ssl_closed` errrors happen due to a bug in Hackney (the HTTP client we use): https://github.com/benoitc/hackney/issues/464

So I'll follow that issue and upgrade hackney when it's been fixed. In the meantime this error exposes that we aren't properly restarting the lua scripting engine if an (unexpected) error occurs. I was working on this in #1035 - I don't think we'll manage to get this done before 1.8.0 is released, but hopefully for 1.8.1. If we get #1035 fixed then you'd still occasionally see the errors, but the lua scripts will keep on working.

**Comment by ramikushnir** [comment] 2019-05-14 11:41
Thank you for attending to this issue. I'll wait for the next version. Is there an estimate as to when 1.8.0 will be released?

**Comment by larshesel** [comment] 2019-05-14 11:43
1.8.0 will likely be released today (or tomorrow) - but it will not contain any fixes for this issue yet.

**Comment by ramikushnir** [comment] 2019-05-14 12:25
Thanks

**Closed** 2019-06-03 07:46 UTC
