### ISSUE TITLE
Vernemq docker image still error loading libsnappy

### ISSUE THREAD

**Issue by lmq1999** [vernemq/vernemq#1540] opened 2020-06-18 08:51 UTC
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

I follow the site here: https://medium.com/@mauri660/kubernetes-mqtt-broker-autoscale-with-custom-metric-1cb9aee0686e

And the github to install vernemq on k8s

### Environment

Kubernetes - install from helm

### Expected behavior

pod running normally

### Actual behaviour

But it keep CrashLoopBackOff even I did accept EULA

Here is the log:

```
08:46:40.853 [info] Application sext exited with reason: stopped
08:46:40.853 [info] Application riak_dt exited with reason: stopped
08:46:40.853 [info] Application eleveldb exited with reason: stopped
08:46:40.854 [error] Loading of /vernemq/bin/../lib/vmq_plumtree-1.10.2/ebin/vmq_plumtree.beam failed: not_purged
08:46:40.859 [warning] The on_load function for module eleveldb returned:
{error,{load_failed,"Failed to load NIF library: 'Error loading shared library libsnappy.so.1: No such file or directory (needed by /vernemq/bin/../lib/eleveldb-2.0.2+build.552.ref06fefb8/priv/eleveldb.so)'"}}

```

I see the problems in  #199 docker-vernemq fix the libsnappy but i still got error, any help ?

**Comment by codeadict** [comment] 2020-06-18 13:19
What version of the VerneMQ docker image do you use?

**Comment by codeadict** [comment] 2020-06-18 13:40
Duplicate of https://github.com/vernemq/docker-vernemq/issues/214

**Comment by codeadict** [comment] 2020-06-18 20:24
this can be closed now @ioolkos

**Closed** 2020-06-20 16:41 UTC
