### ISSUE TITLE
Websocket listener dont process proxy_protocol option

### ISSUE THREAD

**Issue by mtaobiz** [vernemq/vernemq#1703] opened 2021-01-13 12:32 UTC
### Environment

- VerneMQ Version: 1.11.0
- OS: Debian 10.4
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default

listener.tcp.default = 127.0.0.1:1883
listener.tcp.listener1 = 10.1.4.180:1883
listener.tcp.proxy1 = 10.1.4.180:1884
listener.tcp.proxy1.proxy_protocol = on

listener.ws.default = 0.0.0.0:9002
listener.ws.default.proxy_protocol = on

- Cluster size/standalone:

clustered

### Expected behaviour

Websocket connecttion from browser through nginx and haproxy accepted by vernemq

### Actual behaviour

Error during WebSocket handshake: Unexpected response code: 400

proxy_protocol option ignored in ws listener or don`t work

- Please include minimal steps to reproduce the issue, if possible.

nginx conf:
```
...
upstream ws_proxy {
    least_conn;
    server 127.0.0.1:9002;
}

server {
listen 443 ssl;
...
location /ws_proxy {
    proxy_pass http://ws_proxy/mqtt;
    proxy_redirect          default;
    proxy_pass_request_headers            off;
    proxy_http_version                    1.1;
    proxy_set_header   Host               $host;
    proxy_set_header   Connection         "Upgrade";
    proxy_set_header   Upgrade            $http_upgrade;
    proxy_set_header   User-Agent         $http_user_agent;
    proxy_set_header   Origin             $http_origin;
    proxy_set_header   Sec-WebSocket-Version $http_sec_websocket_version;
    proxy_set_header   Accept-Encoding    $http_accept_encoding;
    proxy_set_header   Accept-Language    $http_accept_language;
    proxy_set_header   Sec-WebSocket-Key  $http_sec_websocket_key;
    proxy_set_header   Sec-WebSocket-Extensions  $http_sec_websocket_extensions;
    proxy_set_header   Sec-WebSocket-Protocol  $http_sec_websocket_protocol;
    proxy_set_header   X-Real-IP          $remote_addr;
    proxy_set_header   X-Forwarded-For    $remote_addr;
    proxy_set_header   X-Forwarded-Proto  $scheme;
}
}
```
haproxy.conf:
```
defaults                            
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000        
        timeout client  50000       
        timeout server  50000  

listen mqtt-proxy
        bind 10.1.4.168:1884
        mode tcp
        option clitcpka # For TCP keep-alive
        timeout client 3h
        timeout server 3h
        option tcplog

        balance leastconn
        server node-2 10.1.4.180:1884 check send-proxy-v2 port 1884 fall 1

frontend bernemq_ws_frontend
        bind 127.0.0.1:9002
        mode http
        default_backend vernemq_ws_backend

backend vernemq_ws_backend
        mode http
        balance leastconn
        server node-2 10.1.4.180:9002 check send-proxy port 9002 fall 1

```
vernemq.conf:
...
```
listener.tcp.default = 127.0.0.1:1883
listener.tcp.listener1 = 10.1.4.180:1883
listener.tcp.proxy1 = 10.1.4.180:1884
listener.tcp.proxy1.proxy_protocol = on

listener.ws.default = 0.0.0.0:9002
listener.ws.default.proxy_protocol = on

```

When I connects from console client to 10.1.4.168:1884 (HAProxy mqtt protocol port) all works as expected: vernemq receives conection, source ip used from proxy protocol header.
When I connects from browser to nginx location /ws_proxy through websockets I receive HTTP status 400.
When I remove "send-proxy" option from "backend vernemq_ws_backend"/"server" connection successful, but vernemq uses client IP of nginx/haproxy host.

One of this needed:
1 Correct handling of proxy_protocol in ws listener
2 In ws listener use client ip from http-forwarded-for http header

**Comment by ioolkos** [comment] 2021-01-13 14:16
@mtaobiz can you check outgoing protocol support for NGINX, and how to configure? sending X-Forward headers is not proxy protocol.
For HAProxy, I don't see why your config does not work. Is that based on an example for outgoing proxy protocol configuration? 
Btw, do you see any errors logged on Verne when those requests arrive?

**Comment by mtaobiz** [comment] 2021-01-13 14:51
I dont see any errors in vernemq logs. log.console.level = debug
This is tcp dump on 9002 port:
```
15:50:35.155256 IP 10.1.4.168.41036 > 10.1.4.180.9002: Flags [P.], seq 1:295, ack 1, win 510, options [nop,nop,TS val 1419605122 ecr 1776944318], length 294
        0x0000:  4500 015a 3066 4000 4006 ebda 0a01 04a8  E..Z0f@.@.......
        0x0010:  0a01 04b4 a04c 232a 0d1f 88eb e766 2e4b  .....L#*.....f.K
        0x0020:  8018 01fe fd20 0000 0101 080a 549d 7482  ............T.t.
        0x0030:  69ea 04be 5052 4f58 5920 5443 5034 2031  i...PROXY.TCP4.1
        0x0040:  3237 2e30 2e30 2e31 2031 3237 2e30 2e30  27.0.0.1.127.0.0
        0x0050:  2e31 2034 3435 3436 2039 3030 320d 0a47  .1.44546.9002..G
        0x0060:  4554 202f 6d71 7474 2048 5454 502f 312e  ET./mqtt.HTTP/1.
        0x0070:  310d 0a43 6f6e 6e65 6374 696f 6e3a 2055  1..Connection:.U
        0x0080:  7067 7261 6465 0d0a 5570 6772 6164 653a  pgrade..Upgrade:
        0x0090:  2077 6562 736f 636b 6574 0d0a 5365 632d  .websocket..Sec-
        0x00a0:  5765 6253 6f63 6b65 742d 5665 7273 696f  WebSocket-Versio
        0x00b0:  6e3a 2031 330d 0a53 6563 2d57 6562 536f  n:.13..Sec-WebSo
        0x00c0:  636b 6574 2d4b 6579 3a20 4435 5854 4441  cket-Key:.D5XTDA
        0x00d0:  664d 7a42 334e 4b77 7578 3554 2b77 4441  fMzB3NKwux5T+wDA
        0x00e0:  3d3d 0d0a 5365 632d 5765 6253 6f63 6b65  ==..Sec-WebSocke
        0x00f0:  742d 4578 7465 6e73 696f 6e73 3a20 7065  t-Extensions:.pe
        0x0100:  726d 6573 7361 6765 2d64 6566 6c61 7465  rmessage-deflate
        0x0110:  3b20 636c 6965 6e74 5f6d 6178 5f77 696e  ;.client_max_win
        0x0120:  646f 775f 6269 7473 0d0a 5365 632d 5765  dow_bits..Sec-We
        0x0130:  6253 6f63 6b65 742d 5072 6f74 6f63 6f6c  bSocket-Protocol
        0x0140:  3a20 6d71 7474 0d0a 486f 7374 3a20 7773  :.mqtt..Host:.ws
        0x0150:  5f70 726f 7879 0d0a 0d0a                 _proxy....
15:50:35.155262 IP 10.1.4.180.9002 > 10.1.4.168.41036: Flags [.], ack 295, win 504, options [nop,nop,TS val 1776944318 ecr 1419605122], length 0
        0x0000:  4500 0034 fbc1 4000 4006 21a5 0a01 04b4  E..4..@.@.!.....
        0x0010:  0a01 04a8 232a a04c e766 2e4b 0d1f 8a11  ....#*.L.f.K....
        0x0020:  8010 01f8 1d84 0000 0101 080a 69ea 04be  ............i...
        0x0030:  549d 7482                                T.t.
15:50:35.155764 IP 10.1.4.180.9002 > 10.1.4.168.41036: Flags [P.], seq 1:67, ack 295, win 504, options [nop,nop,TS val 1776944318 ecr 1419605122], length 66
        0x0000:  4500 0076 fbc2 4000 4006 2162 0a01 04b4  E..v..@.@.!b....
        0x0010:  0a01 04a8 232a a04c e766 2e4b 0d1f 8a11  ....#*.L.f.K....
        0x0020:  8018 01f8 1dc6 0000 0101 080a 69ea 04be  ............i...
        0x0030:  549d 7482 4854 5450 2f31 2e31 2034 3030  T.t.HTTP/1.1.400
        0x0040:  2042 6164 2052 6571 7565 7374 0d0a 636f  .Bad.Request..co
        0x0050:  6e6e 6563 7469 6f6e 3a20 636c 6f73 650d  nnection:.close.
        0x0060:  0a63 6f6e 7465 6e74 2d6c 656e 6774 683a  .content-length:
        0x0070:  2030 0d0a 0d0a                           .0....
```

**Comment by mtaobiz** [comment] 2021-01-13 14:55
I know what X-Forwarded-For is not proxy protocol. Currently I seeking config for HAProxy to convert X-Forwarded-For to proxy protocol header... Or may be its possible in NGINX ? If not, support for X-Forwarded-For in vernemq ws listener needed...

**Comment by mtaobiz** [comment] 2021-01-13 14:58
This is tcpdump WITHOUT send-proxy option:
```
15:56:35.074557 IP 10.1.4.168.47646 > 10.1.4.180.9002: Flags [P.], seq 1:252, ack 1, win 510, options [nop,nop,TS val 1419965035 ecr 1777304229], length 251
        0x0000:  4500 012f 899e 4000 4006 92cd 0a01 04a8  E../..@.@.......
        0x0010:  0a01 04b4 ba1e 232a 519f 4c14 ab24 a46a  ......#*Q.L..$.j
        0x0020:  8018 01fe 2a32 0000 0101 080a 54a2 f26b  ....*2......T..k
        0x0030:  69ef 82a5 4745 5420 2f6d 7174 7420 4854  i...GET./mqtt.HT
        0x0040:  5450 2f31 2e31 0d0a 436f 6e6e 6563 7469  TP/1.1..Connecti
        0x0050:  6f6e 3a20 5570 6772 6164 650d 0a55 7067  on:.Upgrade..Upg
        0x0060:  7261 6465 3a20 7765 6273 6f63 6b65 740d  rade:.websocket.
        0x0070:  0a53 6563 2d57 6562 536f 636b 6574 2d56  .Sec-WebSocket-V
        0x0080:  6572 7369 6f6e 3a20 3133 0d0a 5365 632d  ersion:.13..Sec-
        0x0090:  5765 6253 6f63 6b65 742d 4b65 793a 204d  WebSocket-Key:.M
        0x00a0:  4970 5733 5831 3332 6b4b 7738 6547 624b  IpW3X132kKw8eGbK
        0x00b0:  4b74 6f33 773d 3d0d 0a53 6563 2d57 6562  Kto3w==..Sec-Web
        0x00c0:  536f 636b 6574 2d45 7874 656e 7369 6f6e  Socket-Extension
        0x00d0:  733a 2070 6572 6d65 7373 6167 652d 6465  s:.permessage-de
        0x00e0:  666c 6174 653b 2063 6c69 656e 745f 6d61  flate;.client_ma
        0x00f0:  785f 7769 6e64 6f77 5f62 6974 730d 0a53  x_window_bits..S
        0x0100:  6563 2d57 6562 536f 636b 6574 2d50 726f  ec-WebSocket-Pro
        0x0110:  746f 636f 6c3a 206d 7174 740d 0a48 6f73  tocol:.mqtt..Hos
        0x0120:  743a 2077 735f 7072 6f78 790d 0a0d 0a    t:.ws_proxy....
15:56:35.074567 IP 10.1.4.180.9002 > 10.1.4.168.47646: Flags [.], ack 252, win 504, options [nop,nop,TS val 1777304229 ecr 1419965035], length 0
        0x0000:  4500 0034 f0b1 4000 4006 2cb5 0a01 04b4  E..4..@.@.,.....
        0x0010:  0a01 04a8 232a ba1e ab24 a46a 519f 4d0f  ....#*...$.jQ.M.
        0x0020:  8010 01f8 1d84 0000 0101 080a 69ef 82a5  ............i...
        0x0030:  54a2 f26b                                T..k
15:56:35.075143 IP 10.1.4.180.9002 > 10.1.4.168.47646: Flags [P.], seq 1:286, ack 252, win 504, options [nop,nop,TS val 1777304230 ecr 1419965035], length 285
        0x0000:  4500 0151 f0b2 4000 4006 2b97 0a01 04b4  E..Q..@.@.+.....
        0x0010:  0a01 04a8 232a ba1e ab24 a46a 519f 4d0f  ....#*...$.jQ.M.
        0x0020:  8018 01f8 1ea1 0000 0101 080a 69ef 82a6  ............i...
        0x0030:  54a2 f26b 4854 5450 2f31 2e31 2031 3031  T..kHTTP/1.1.101
        0x0040:  2053 7769 7463 6869 6e67 2050 726f 746f  .Switching.Proto
        0x0050:  636f 6c73 0d0a 636f 6e6e 6563 7469 6f6e  cols..connection
        0x0060:  3a20 5570 6772 6164 650d 0a64 6174 653a  :.Upgrade..date:
        0x0070:  2057 6564 2c20 3133 204a 616e 2032 3032  .Wed,.13.Jan.202
        0x0080:  3120 3134 3a35 363a 3334 2047 4d54 0d0a  1.14:56:34.GMT..
        0x0090:  7365 632d 7765 6273 6f63 6b65 742d 6163  sec-websocket-ac
        0x00a0:  6365 7074 3a20 4b33 3851 4a69 6f53 556e  cept:.K38QJioSUn
        0x00b0:  7657 6253 7763 642b 6941 6650 2b76 4458  vWbSwcd+iAfP+vDX
        0x00c0:  413d 0d0a 7365 632d 7765 6273 6f63 6b65  A=..sec-websocke
        0x00d0:  742d 6578 7465 6e73 696f 6e73 3a20 7065  t-extensions:.pe
        0x00e0:  726d 6573 7361 6765 2d64 6566 6c61 7465  rmessage-deflate
        0x00f0:  3b20 636c 6965 6e74 5f6d 6178 5f77 696e  ;.client_max_win
        0x0100:  646f 775f 6269 7473 3d31 350d 0a73 6563  dow_bits=15..sec
        0x0110:  2d77 6562 736f 636b 6574 2d70 726f 746f  -websocket-proto
        0x0120:  636f 6c3a 206d 7174 740d 0a73 6572 7665  col:.mqtt..serve
        0x0130:  723a 2043 6f77 626f 790d 0a75 7067 7261  r:.Cowboy..upgra
        0x0140:  6465 3a20 7765 6273 6f63 6b65 740d 0a0d  de:.websocket...
        0x0150:  0a                        
```

**Comment by ioolkos** [comment] 2021-01-17 09:49
@mtaobiz keep us updated when you find a working setup with NGINX/HAProxy.
If you want me to stay on this, please provide proper capture files.

**Comment by kushwiz** [comment] 2021-02-17 06:32
@ioolkos 
I see this problem on WS listener using proxy protocol.  But it works just fine with MQTT plain TCP proxy protocol listener. I am using only HAProxy as my LB. There is no difference in the ProxyV2 packet sent to vernemq. Could you check this at your end? Thanks.

Error when using WS with proxy protocol on Vernemq
```
Client 'UNKNOWN@127.0.0.1' DISCONNECTED Invalid handshake response getStatus: 400 Bad Request
```


This HAProxy config just uses plain TCP mode, so no difference if I use WS or TCP listener on vernemq
```
global
  maxconn 2000
  log stdout local0 debug

defaults
 log global
 option httplog
 timeout queue 30s
 timeout connect 30s
 timeout client 180s
 timeout server 180s
 timeout check 10s

frontend wss
  bind 0.0.0.0:9004 ssl crt /etc/haproxy/server.pem ca-file /etc/haproxy/ca.crt verify required
  mode tcp
  option clitcpka
  option tcplog
  default_backend mqtt_ws

backend mqtt_ws
  mode tcp
  server mqtt1 192.168.0.1:9002 send-proxy-v2-ssl-cn port 9002 fall 1

```

vernemq (TCP working config)
```
########## Start ##########
accept_eula=yes
listener.tcp.allowed_protocol_versions=3,4,5
log.console.level=debug
listener.tcp.nr_of_acceptors=100
listener.tcp.default.proxy_protocol_use_cn_as_username=on
listener.tcp.default=0.0.0.0:9002
allow_anonymous=on
listener.tcp.default.proxy_protocol=on
log.console=console
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.ws.default = 172.19.0.3:8080
listener.vmq.clustering = 172.19.0.3:44053
listener.http.metrics = 172.19.0.3:8888
########## End ##########
```

Vernemq config WS NOT working:
```
########## Start ##########
accept_eula=yes
listener.tcp.allowed_protocol_versions=3,4,5
log.console.level=debug
listener.ws.nr_of_acceptors=100
listener.ws.default.proxy_protocol_use_cn_as_username=on
listener.ws.default=0.0.0.0:9002
allow_anonymous=on
listener.ws.default.proxy_protocol=on
log.console=console
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.vmq.clustering = 172.19.0.3:44053
listener.http.metrics = 172.19.0.3:8888
########## End ##########
```

**Comment by ioolkos** [comment] 2021-02-21 12:27
@mtaobiz @kushwiz just tested this & confirming there's some issue with proxy enabled WS listener. Let me try to understand it.

**Comment by ioolkos** [comment] 2021-02-21 12:51
Note to self: ![ws_proxy_prot](https://user-images.githubusercontent.com/282359/108625528-b13f0a80-744b-11eb-8814-75734d0b483c.png)

**Comment by ioolkos** [comment] 2021-02-21 18:17
![proxy_websocket_error](https://user-images.githubusercontent.com/282359/108634326-663bec00-7479-11eb-9add-7905579bda03.png)

**Comment by ioolkos** [comment] 2021-02-21 18:22
Current status: why has this ever worked, and why have users confirmed it does work? :)

**Comment by ioolkos** [comment] 2021-02-22 07:49
Note to self: remove dead code: https://github.com/vernemq/vernemq/blob/537049242c8bb30a9dafe77c48e0af67d9ef12b5/apps/vmq_server/src/vmq_ranch.erl#L134

**Comment by ioolkos** [comment] 2021-02-23 15:44
@kushwiz @mtaobiz I think I understand what's happening. Working on a fix.

**Comment by ioolkos** [comment] 2021-02-27 12:04
@kushwiz @mtaobiz are you able to build Verne from a PR? if yes, feel free to test https://github.com/vernemq/vernemq/pull/1739 it'd be great to know whether this fixes the proxy protocol for your use case.

**Comment by kushwiz** [comment] 2021-03-01 18:26
@ioolkos  give me 2 days

**Comment by ioolkos** [comment] 2021-03-15 07:49
@kushwiz have you been able to test yet? no hurry at all, I think the PR fixes the issue, it'd just be great to have another confirm before I merge.

**Comment by ioolkos** [comment] 2021-04-02 07:57
Since nobody seems to have the time or need to test this, I'm closing this as fixed.

**Closed by ioolkos** 2021-04-02 07:57 UTC
Labels: need more data, proxy_protocol, websocket
